package installations

import "time"

// Installation represents a managed WordPress deployment.
type Installation struct {
	ID                       string    `json:"id"`
	Type                     string    `json:"type"`
	Domain                   string    `json:"domain"`
	InstallPath              string    `json:"installPath"`
	SitePath                 string    `json:"sitePath"`
	URL                      string    `json:"url"`
	AdminURL                 string    `json:"adminUrl"`
	SiteTitle                string    `json:"siteTitle"`
	AdminUser                string    `json:"adminUser"`
	AdminPassword            string    `json:"adminPassword"`
	AdminEmail               string    `json:"adminEmail"`
	DBName                   string    `json:"dbName"`
	DBUser                   string    `json:"dbUser"`
	DBPassword               string    `json:"dbPassword"`
	CredentialsAutoGenerated bool      `json:"credentialsAutoGenerated"`
	Status                   string    `json:"status"`
	Message                  string    `json:"message"`
	CreatedAt                time.Time `json:"createdAt"`
	UpdatedAt                time.Time `json:"updatedAt"`
}
