package installations

import (
	"context"
	"crypto/rand"
	"fmt"
	"strings"
	"time"

	"github.com/Harsh223/PanelX/apps/control-plane/internal/provision"
)

// Service coordinates provisioning and installation metadata persistence.
type Service struct {
	store            Store
	provisionService *provision.Service
}

// NewService creates an installation service.
func NewService(store Store, provisionService *provision.Service) *Service {
	return &Service{store: store, provisionService: provisionService}
}

// CreateWordPress provisions WordPress and stores installation metadata.
func (s *Service) CreateWordPress(ctx context.Context, req provision.WordPressInstallRequest) (Installation, error) {
	result, err := s.provisionService.InstallWordPress(ctx, req)
	if err != nil {
		return Installation{}, err
	}

	now := time.Now().UTC()
	installation := Installation{
		ID:                       newID(),
		Type:                     "wordpress",
		Domain:                   result.Domain,
		InstallPath:              result.InstallPath,
		SitePath:                 result.SitePath,
		URL:                      result.URL,
		AdminURL:                 result.AdminURL,
		SiteTitle:                result.SiteTitle,
		AdminUser:                result.AdminUser,
		AdminPassword:            result.AdminPassword,
		AdminEmail:               result.AdminEmail,
		DBName:                   result.DBName,
		DBUser:                   result.DBUser,
		DBPassword:               result.DBPassword,
		CredentialsAutoGenerated: result.CredentialsAutoGenerated,
		Status:                   "active",
		Message:                  result.Message,
		CreatedAt:                now,
		UpdatedAt:                now,
	}

	if err := s.store.Create(installation); err != nil {
		return Installation{}, err
	}

	return installation, nil
}

// List returns all recorded installations.
func (s *Service) List() ([]Installation, error) {
	return s.store.List()
}

// Get retrieves one installation by id.
func (s *Service) Get(id string) (Installation, bool, error) {
	return s.store.GetByID(strings.TrimSpace(id))
}

func newID() string {
	buf := make([]byte, 8)
	_, _ = rand.Read(buf)
	return fmt.Sprintf("inst-%d-%x", time.Now().UTC().Unix(), buf)
}
