import type { CSSProperties } from "react";
import type { ThemeTokens } from "./themeTypes";

export type AppStage = "loading" | "bootstrap" | "login" | "app";

export type ViewMode =
  | "dashboard"
  | "domains"
  | "wordpress"
  | "sites"
  | "domainLogs"
  | "files"
  | "onboarding"
  | "home"
  | "launchAssistant"
  | "help"
  | "system";

export type OnboardingStep = 1 | 2 | 3;
export type LaunchAssistantStep = 1 | 2 | 3 | 4;

export type AdminProfile = {
  username: string;
  email: string;
  createdAt: string;
  updatedAt: string;
};

export type AuthStatusResponse = {
  configured: boolean;
  admin?: AdminProfile;
};

export type PanelMeResponse = {
  authenticated: boolean;
  admin?: AdminProfile;
  session?: {
    username: string;
    expiresAt: string;
  };
};

export type ServiceStatus = {
  name: string;
  active: boolean;
  state: string;
  description?: string;
};

export type DiskStatus = {
  path: string;
  filesystem: string;
  totalBytes: number;
  usedBytes: number;
  freeBytes: number;
  usedPercent: number;
};

export type NetworkStatus = {
  name: string;
  rxBytes: number;
  txBytes: number;
  receiveErrors: number;
  transmitErrors: number;
};

export type SystemSnapshot = {
  status: string;
  timestamp: string;
  hostname: string;
  os: string;
  arch: string;
  kernel: string;
  uptime: { seconds: number; human: string };
  load: { one: number; five: number; fifteen: number };
  cpu: {
    cores: number;
    usagePercent: number;
    sampleWindow: string;
    usageMeasured: boolean;
  };
  memory: {
    totalBytes: number;
    availableBytes: number;
    usedBytes: number;
    usedPercent: number;
    swapTotalBytes: number;
    swapFreeBytes: number;
    swapUsedBytes: number;
    swapUsedPercent: number;
  };
  disk: DiskStatus[];
  services: ServiceStatus[];
  network: NetworkStatus[];
  wordpress: {
    sitesRoot: string;
    detectedSites: number;
    installStoreOk: boolean;
    phpSocketFound: boolean;
  };
  warnings?: string[];
  collectedMs: number;
};

export type Installation = {
  id: string;
  type: string;
  domain: string;
  installPath: string;
  sitePath: string;
  url: string;
  adminUrl: string;
  siteTitle: string;
  adminUser: string;
  adminPassword: string;
  adminEmail: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  credentialsAutoGenerated: boolean;
  status: string;
  message: string;
  createdAt: string;
  updatedAt: string;
};

export type FileEntry = {
  name: string;
  path: string;
  isDir: boolean;
  size: number;
};

export type FileBreadcrumb = {
  label: string;
  path: string;
};

export type DomainRecord = {
  id: string;
  hostname: string;
  rootDomain?: string;
  isSubdomain: boolean;
  documentRoot: string;
  sitePath?: string;
  ownerLabel?: string;
  notes?: string;
  status: "pending" | "active" | "degraded" | "disabled" | "error";
  tls: {
    enabled: boolean;
    provider: "letsencrypt" | "manual";
    status:
      | "none"
      | "pending"
      | "issued"
      | "expiring"
      | "expired"
      | "failed"
      | "revoked"
      | "unknown";
    autoRenew: boolean;
    certificateCn?: string;
    issuedAt?: string;
    expiresAt?: string;
    lastAttemptAt?: string;
    lastError?: string;
    lastErrorCode?: string;
    renewalWindowInDays?: number;
  };
  redirects: {
    mode: "off" | "http_to_https" | "custom";
    canonicalHost: "none" | "root" | "www" | "custom";
    canonicalTarget?: string;
    customTargetUrl?: string;
    preservePath: boolean;
    preserveQuery: boolean;
    temporary: boolean;
  };
  health: {
    resolvesToServerIp: boolean;
    resolvedIps?: string[];
    nginxConfigPresent: boolean;
    nginxEnabled: boolean;
    lastCheckedAt: string;
    warnings?: string[];
  };
  createdAt: string;
  updatedAt: string;
  lastSyncedAt?: string;
};

export type DomainCreateForm = {
  hostname: string;
  documentRoot: string;
  ownerLabel: string;
  notes: string;
  enableNginx: boolean;
};

export type DomainRedirectForm = {
  mode: "off" | "http_to_https" | "custom";
  canonicalHost: "none" | "root" | "www" | "custom";
  canonicalTarget: string;
  customTargetUrl: string;
  preservePath: boolean;
  preserveQuery: boolean;
  temporary: boolean;
};

export type WordPressRequest = {
  domain: string;
  installPath: string;
  siteTitle: string;
  adminEmail: string;
  adminUser: string;
  adminPassword: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
};

export type SetupForm = {
  bootstrapToken: string;
  username: string;
  email: string;
  password: string;
  confirmPassword: string;
};

export type LoginForm = {
  username: string;
  password: string;
};

export type ToastMessage = {
  id: number;
  kind: "success" | "error" | "info";
  text: string;
};

export type OnboardingSummary = {
  summary: string;
  nextStep: string;
  ready: boolean;
};

export type LaunchAssistantProgress = {
  domainReady: boolean;
  sslReady: boolean;
  wordpressReady: boolean;
  completedSteps: number;
  totalSteps: number;
  nextStep: LaunchAssistantStep;
  ctaLabel: string;
};

export type CommonPanelStyleProps = {
  colors: ThemeTokens;
  isCompact: boolean;
  panelStyle: (colors: ThemeTokens) => CSSProperties;
  gridCards?: (columns: number) => CSSProperties;
  inputStyle?: (colors: ThemeTokens) => CSSProperties;
  primaryButton: (colors: ThemeTokens) => CSSProperties;
  ghostButton: (colors: ThemeTokens) => CSSProperties;
  dangerButton?: (colors: ThemeTokens) => CSSProperties;
};

export type LaunchAssistantPanelProps = CommonPanelStyleProps & {
  launchAssistantStep: LaunchAssistantStep;
  launchAssistantProgress: LaunchAssistantProgress;
  onboardingSummary: OnboardingSummary;
  showOnboardingWizard: boolean;
  launchAssistantDomain: string;
  selectedLaunchDomain: DomainRecord | null;
  authenticatedAdmin: AdminProfile | null;
  setLaunchAssistantStep: (step: LaunchAssistantStep) => void;
  setLaunchAssistantDomain: (value: string) => void;
  setSelectedDomain: (domain: DomainRecord | null) => void;
  setInstallForm: (
    updater: (prev: WordPressRequest) => WordPressRequest,
  ) => void;
  setFileDomain: (value: string) => void;
  setFilePath: (value: string) => void;
  setView: (view: ViewMode) => void;
  runDomainHealth: (id?: string) => Promise<void>;
  copyDNSChecklist: (domain: DomainRecord) => Promise<void>;
  openDomainSite: (domain: DomainRecord) => void;
  openDomainAdmin: (domain: DomainRecord) => void;
};

export type SitesPanelProps = CommonPanelStyleProps & {
  gridCards: (columns: number) => CSSProperties;
  installations: Installation[];
  selectedInstall: Installation | null;
  setSelectedInstall: (install: Installation | null) => void;
  setFileDomain: (value: string) => void;
  setFilePath: (value: string) => void;
  setView: (view: ViewMode) => void;
  loadInstallations: (report?: boolean) => Promise<void>;
};

export type FilesPanelProps = CommonPanelStyleProps & {
  inputStyle: (colors: ThemeTokens) => CSSProperties;
  dangerButton: (colors: ThemeTokens) => CSSProperties;
  fileDomain: string;
  filePath: string;
  entries: FileEntry[];
  selectedPath: string;
  fileContent: string;
  pendingDeletePath: string;
  fileQuickPaths: string[];
  fileBreadcrumbs: FileBreadcrumb[];
  setFileDomain: (value: string) => void;
  setFilePath: (value: string) => void;
  setFileContent: (value: string) => void;
  setPendingDeletePath: (value: string) => void;
  listFiles: (nextPath?: string) => Promise<void>;
  openFile: (path: string) => Promise<void>;
  saveFile: () => Promise<void>;
  deletePath: (path: string) => Promise<void>;
};

export type HelpPanelProps = CommonPanelStyleProps & {
  setView: (view: ViewMode) => void;
};
