import React, { useEffect, useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import LaunchAssistantPanel from "./ui/panels/LaunchAssistantPanel";
import SitesPanel from "./ui/panels/SitesPanel";
import FilesPanel from "./ui/panels/FilesPanel";
import HelpPanel from "./ui/panels/HelpPanel";
import ToastStack from "./ui/shared/ToastStack";
import { Metric, CredentialItem } from "./ui/shared/DataCards";
import { apiFetch, errorMessage } from "./ui/shared/api";
import { formatBytes, timeAgo } from "./ui/shared/format";
import { isLikelyDomainOrIP, isValidEmail } from "./ui/shared/validators";
import {
  sectionTitle,
  panelStyle,
  metricCard,
  serviceCard,
  inputStyle,
  primaryButton,
  ghostButton,
  dangerButton,
  tableHeader,
  tableCell,
  filePane,
  gridCards,
  logoBadge,
  mobileQuickNavButtonStyle,
} from "./ui/shared/styleSystem";

type ThemeMode = "light" | "dark";
type AppStage = "loading" | "bootstrap" | "login" | "app";
type ViewMode =
  | "dashboard"
  | "domains"
  | "wordpress"
  | "sites"
  | "domainLogs"
  | "files"
  | "onboarding"
  | "home"
  | "launchAssistant"
  | "help"
  | "system";

type AdminProfile = {
  username: string;
  email: string;
  createdAt: string;
  updatedAt: string;
};

type AuthStatusResponse = {
  configured: boolean;
  admin?: AdminProfile;
};

type PanelMeResponse = {
  authenticated: boolean;
  admin?: AdminProfile;
  session?: {
    username: string;
    expiresAt: string;
  };
};

type ServiceStatus = {
  name: string;
  active: boolean;
  state: string;
  description?: string;
};

type DiskStatus = {
  path: string;
  filesystem: string;
  totalBytes: number;
  usedBytes: number;
  freeBytes: number;
  usedPercent: number;
};

type NetworkStatus = {
  name: string;
  rxBytes: number;
  txBytes: number;
  receiveErrors: number;
  transmitErrors: number;
};

type SystemSnapshot = {
  status: string;
  timestamp: string;
  hostname: string;
  os: string;
  arch: string;
  kernel: string;
  uptime: { seconds: number; human: string };
  load: { one: number; five: number; fifteen: number };
  cpu: {
    cores: number;
    usagePercent: number;
    sampleWindow: string;
    usageMeasured: boolean;
  };
  memory: {
    totalBytes: number;
    availableBytes: number;
    usedBytes: number;
    usedPercent: number;
    swapTotalBytes: number;
    swapFreeBytes: number;
    swapUsedBytes: number;
    swapUsedPercent: number;
  };
  disk: DiskStatus[];
  services: ServiceStatus[];
  network: NetworkStatus[];
  wordpress: {
    sitesRoot: string;
    detectedSites: number;
    installStoreOk: boolean;
    phpSocketFound: boolean;
  };
  warnings?: string[];
  collectedMs: number;
};

type Installation = {
  id: string;
  type: string;
  domain: string;
  installPath: string;
  sitePath: string;
  url: string;
  adminUrl: string;
  siteTitle: string;
  adminUser: string;
  adminPassword: string;
  adminEmail: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  credentialsAutoGenerated: boolean;
  status: string;
  message: string;
  createdAt: string;
  updatedAt: string;
};

type FileEntry = {
  name: string;
  path: string;
  isDir: boolean;
  size: number;
};

type DomainRecord = {
  id: string;
  hostname: string;
  rootDomain?: string;
  isSubdomain: boolean;
  documentRoot: string;
  sitePath?: string;
  ownerLabel?: string;
  notes?: string;
  status: "pending" | "active" | "degraded" | "disabled" | "error";
  tls: {
    enabled: boolean;
    provider: "letsencrypt" | "manual";
    status:
      | "none"
      | "pending"
      | "issued"
      | "expiring"
      | "expired"
      | "failed"
      | "revoked"
      | "unknown";
    autoRenew: boolean;
    certificateCn?: string;
    issuedAt?: string;
    expiresAt?: string;
    lastAttemptAt?: string;
    lastError?: string;
    lastErrorCode?: string;
    renewalWindowInDays?: number;
  };
  redirects: {
    mode: "off" | "http_to_https" | "custom";
    canonicalHost: "none" | "root" | "www" | "custom";
    canonicalTarget?: string;
    customTargetUrl?: string;
    preservePath: boolean;
    preserveQuery: boolean;
    temporary: boolean;
  };
  health: {
    resolvesToServerIp: boolean;
    resolvedIps?: string[];
    nginxConfigPresent: boolean;
    nginxEnabled: boolean;
    lastCheckedAt: string;
    warnings?: string[];
  };
  createdAt: string;
  updatedAt: string;
  lastSyncedAt?: string;
};

type DomainCreateForm = {
  hostname: string;
  documentRoot: string;
  ownerLabel: string;
  notes: string;
  enableNginx: boolean;
};

type DomainRedirectForm = {
  mode: "off" | "http_to_https" | "custom";
  canonicalHost: "none" | "root" | "www" | "custom";
  canonicalTarget: string;
  customTargetUrl: string;
  preservePath: boolean;
  preserveQuery: boolean;
  temporary: boolean;
};

type OnboardingStep = 1 | 2 | 3;
type LaunchAssistantStep = 1 | 2 | 3 | 4;

type WordPressRequest = {
  domain: string;
  installPath: string;
  siteTitle: string;
  adminEmail: string;
  adminUser: string;
  adminPassword: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
};

type SetupForm = {
  bootstrapToken: string;
  username: string;
  email: string;
  password: string;
  confirmPassword: string;
};

type LoginForm = {
  username: string;
  password: string;
};

type ToastMessage = {
  id: number;
  kind: "success" | "error" | "info";
  text: string;
};

type ThemeTokens = {
  bg: string;
  panel: string;
  panelAlt: string;
  border: string;
  borderSoft: string;
  text: string;
  textMuted: string;
  primary: string;
  primarySoft: string;
  danger: string;
  success: string;
  shadow: string;
  inset: string;
};

const lightTheme: ThemeTokens = {
  bg: "radial-gradient(1000px 600px at 10% -20%, #f8fbff 0%, #edf2fb 50%, #e2e8f0 100%)",
  panel: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)",
  panelAlt: "linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)",
  border: "#cbd5e1",
  borderSoft: "#e2e8f0",
  text: "#0f172a",
  textMuted: "#475569",
  primary: "#2563eb",
  primarySoft: "#dbeafe",
  danger: "#b91c1c",
  success: "#15803d",
  shadow: "0 16px 38px rgba(15,23,42,0.12)",
  inset: "inset 0 1px 0 rgba(255,255,255,0.8)",
};

const darkTheme: ThemeTokens = {
  bg: "radial-gradient(1100px 700px at 20% -20%, #263b7d 0%, #0b1220 55%, #060a12 100%)",
  panel: "linear-gradient(180deg, #111827 0%, #0f172a 100%)",
  panelAlt: "linear-gradient(180deg, #1e293b 0%, #0f172a 100%)",
  border: "#334155",
  borderSoft: "#1f2937",
  text: "#e2e8f0",
  textMuted: "#94a3b8",
  primary: "#3b82f6",
  primarySoft: "#1e3a8a",
  danger: "#ef4444",
  success: "#22c55e",
  shadow: "0 20px 50px rgba(0,0,0,0.45)",
  inset: "inset 0 1px 0 rgba(255,255,255,0.06)",
};

function App() {
  const [theme, setTheme] = useState<ThemeMode>(() => {
    const saved = localStorage.getItem("panelx-theme");
    return saved === "dark" ? "dark" : "light";
  });
  const [stage, setStage] = useState<AppStage>("loading");
  const [view, setView] = useState<ViewMode>("home");
  const [status, setStatus] = useState("Loading PanelX...");
  const [authenticatedAdmin, setAuthenticatedAdmin] =
    useState<AdminProfile | null>(null);

  const [beginnerMode, setBeginnerMode] = useState(true);
  const [launchAssistantStep, setLaunchAssistantStep] =
    useState<LaunchAssistantStep>(1);
  const [launchAssistantDomain, setLaunchAssistantDomain] = useState("");

  const [setupForm, setSetupForm] = useState<SetupForm>({
    bootstrapToken: "",
    username: "admin",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const [loginForm, setLoginForm] = useState<LoginForm>({
    username: "admin",
    password: "",
  });

  const [autoRefresh, setAutoRefresh] = useState(true);
  const [refreshSeconds, setRefreshSeconds] = useState(15);
  const [isCompact, setIsCompact] = useState(() => window.innerWidth < 1100);

  const [system, setSystem] = useState<SystemSnapshot | null>(null);
  const [installations, setInstallations] = useState<Installation[]>([]);
  const [selectedInstall, setSelectedInstall] = useState<Installation | null>(
    null,
  );

  const [installForm, setInstallForm] = useState<WordPressRequest>({
    domain: "",
    installPath: "/",
    siteTitle: "",
    adminEmail: "",
    adminUser: "",
    adminPassword: "",
    dbName: "",
    dbUser: "",
    dbPassword: "",
  });

  const [fileDomain, setFileDomain] = useState("");
  const [filePath, setFilePath] = useState("");
  const [entries, setEntries] = useState<FileEntry[]>([]);
  const [selectedPath, setSelectedPath] = useState("");
  const [fileContent, setFileContent] = useState("");
  const [pendingDeletePath, setPendingDeletePath] = useState("");
  const [toasts, setToasts] = useState<ToastMessage[]>([]);

  const [domains, setDomains] = useState<DomainRecord[]>([]);
  const [selectedDomain, setSelectedDomain] = useState<DomainRecord | null>(
    null,
  );
  const [domainForm, setDomainForm] = useState<DomainCreateForm>({
    hostname: "",
    documentRoot: "",
    ownerLabel: "",
    notes: "",
    enableNginx: true,
  });
  const [redirectForm, setRedirectForm] = useState<DomainRedirectForm>({
    mode: "off",
    canonicalHost: "none",
    canonicalTarget: "",
    customTargetUrl: "",
    preservePath: true,
    preserveQuery: true,
    temporary: false,
  });
  const [sslEmail, setSslEmail] = useState("");
  const [domainLogsType, setDomainLogsType] = useState<"access" | "error">(
    "access",
  );
  const [domainLogsLines, setDomainLogsLines] = useState(200);
  const [domainLogs, setDomainLogs] = useState<string[]>([]);
  const [showOnboardingWizard, setShowOnboardingWizard] = useState(false);
  const [onboardingStep, setOnboardingStep] = useState<OnboardingStep>(1);
  const [lastDNSChecklistCopiedFor, setLastDNSChecklistCopiedFor] =
    useState("");

  const colors = theme === "light" ? lightTheme : darkTheme;
  const onboardingSummary = useMemo(
    () => buildOnboardingSummary(domains, installations),
    [domains, installations],
  );
  const selectedLaunchDomain = useMemo(() => {
    const target = launchAssistantDomain.trim().toLowerCase();

    if (target) {
      const found = domains.find((d) => d.hostname.toLowerCase() === target);
      if (found) return found;
    }

    if (selectedDomain) {
      const refreshed = domains.find((d) => d.id === selectedDomain.id);
      return refreshed ?? selectedDomain;
    }

    return domains[0] ?? null;
  }, [domains, selectedDomain, launchAssistantDomain]);
  const launchAssistantProgress = useMemo(
    () => buildLaunchAssistantProgress(selectedLaunchDomain, installations),
    [selectedLaunchDomain, installations],
  );
  const fileQuickPaths = useMemo(
    () =>
      fileDomain.trim()
        ? [
            "/",
            "/public_html",
            "/public_html/wp-content",
            "/public_html/wp-content/themes",
            "/public_html/wp-content/plugins",
            "/public_html/wp-content/uploads",
          ]
        : ["/", "/public_html"],
    [fileDomain],
  );
  const fileBreadcrumbs = useMemo(() => {
    const normalized = filePath.trim();
    if (!normalized || normalized === "/") {
      return [{ label: "/", path: "/" }];
    }

    const safe = normalized.startsWith("/")
      ? normalized
      : `/${normalized}`;
    const parts = safe.split("/").filter(Boolean);

    const crumbs = [{ label: "/", path: "/" }];
    let current = "";
    for (const part of parts) {
      current += `/${part}`;
      crumbs.push({ label: part, path: current });
    }

    return crumbs;
  }, [filePath]);

  useEffect(() => {
    setLaunchAssistantStep((current) =>
      current === launchAssistantProgress.nextStep
        ? current
        : launchAssistantProgress.nextStep,
    );
  }, [launchAssistantProgress.nextStep]);

  useEffect(() => {
    localStorage.setItem("panelx-theme", theme);
  }, [theme]);

  useEffect(() => {
    const onResize = () => setIsCompact(window.innerWidth < 1100);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  useEffect(() => {
    void bootstrapSession();
  }, []);

  useEffect(() => {
    if (!selectedDomain) return;
    setRedirectForm({
      mode: selectedDomain.redirects?.mode ?? "off",
      canonicalHost: selectedDomain.redirects?.canonicalHost ?? "none",
      canonicalTarget: selectedDomain.redirects?.canonicalTarget ?? "",
      customTargetUrl: selectedDomain.redirects?.customTargetUrl ?? "",
      preservePath: selectedDomain.redirects?.preservePath ?? true,
      preserveQuery: selectedDomain.redirects?.preserveQuery ?? true,
      temporary: selectedDomain.redirects?.temporary ?? false,
    });
  }, [selectedDomain]);

  useEffect(() => {
    if (stage !== "app" || !autoRefresh) return;
    const ms = Math.max(5, refreshSeconds) * 1000;
    const id = window.setInterval(() => {
      void Promise.all([
        loadSystem(false),
        loadInstallations(false),
        loadDomains(false),
      ]);
    }, ms);
    return () => window.clearInterval(id);
  }, [stage, autoRefresh, refreshSeconds]);

  function pushToast(
    text: string,
    kind: ToastMessage["kind"] = "info",
    durationMs = 2800,
  ): void {
    const id = Date.now() + Math.floor(Math.random() * 1000);
    setToasts((prev) => [...prev, { id, text, kind }]);

    window.setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, durationMs);
  }

  function dismissToast(id: number): void {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }

  async function bootstrapSession(): Promise<void> {
    try {
      const authStatus = await apiFetch<AuthStatusResponse>(
        "/v1/panel/auth/status",
        { method: "GET" },
      );
      if (!authStatus.configured) {
        setStage("bootstrap");
        setStatus("First-time setup required");
        return;
      }

      const me = await apiFetch<PanelMeResponse>("/v1/panel/me", {
        method: "GET",
        credentials: "include",
      }).catch(() => null);

      if (me?.authenticated && me.admin) {
        setAuthenticatedAdmin(me.admin);
        setStage("app");
        setStatus(`Welcome back, ${me.admin.username}`);
        const loadedDomains = await loadDomains(false);
        await Promise.all([loadSystem(false), loadInstallations(false)]);
        updateOnboardingFromDomains(loadedDomains);
      } else {
        setStage("login");
        setStatus("Please sign in");
      }
    } catch (error) {
      setStage("login");
      setStatus(`Initialization failed: ${errorMessage(error)}`);
    }
  }

  async function handleSetup(): Promise<void> {
    if (!setupForm.bootstrapToken.trim()) {
      setStatus("Bootstrap API token is required");
      return;
    }
    if (!setupForm.email.trim()) {
      setStatus("Admin email is required");
      return;
    }
    if (setupForm.password.length < 8) {
      setStatus("Password must be at least 8 characters");
      return;
    }
    if (setupForm.password !== setupForm.confirmPassword) {
      setStatus("Password confirmation does not match");
      return;
    }

    setStatus("Creating admin account...");
    try {
      const resp = await apiFetch<{ configured: boolean; admin: AdminProfile }>(
        "/v1/panel/auth/setup",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-PanelX-Token": setupForm.bootstrapToken.trim(),
          },
          credentials: "include",
          body: JSON.stringify({
            username: setupForm.username.trim(),
            email: setupForm.email.trim(),
            password: setupForm.password,
          }),
        },
      );

      setAuthenticatedAdmin(resp.admin);
      setStage("app");
      setStatus("Panel setup complete. You're signed in.");
      const loadedDomains = await loadDomains(false);
      await Promise.all([loadSystem(false), loadInstallations(false)]);
      updateOnboardingFromDomains(loadedDomains);
    } catch (error) {
      setStatus(`Setup failed: ${errorMessage(error)}`);
    }
  }

  async function handleLogin(): Promise<void> {
    if (!loginForm.username.trim() || !loginForm.password) {
      setStatus("Username and password are required");
      return;
    }

    setStatus("Signing in...");
    try {
      await apiFetch("/v1/panel/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(loginForm),
      });

      const me = await apiFetch<PanelMeResponse>("/v1/panel/me", {
        method: "GET",
        credentials: "include",
      });

      if (!me.authenticated || !me.admin) {
        throw new Error("Session not established");
      }

      setAuthenticatedAdmin(me.admin);
      setStage("app");
      setStatus(`Welcome, ${me.admin.username}`);
      const loadedDomains = await loadDomains(false);
      await Promise.all([loadSystem(false), loadInstallations(false)]);
      updateOnboardingFromDomains(loadedDomains);
    } catch (error) {
      setStatus(`Login failed: ${errorMessage(error)}`);
    }
  }

  async function handleLogout(): Promise<void> {
    try {
      await apiFetch("/v1/panel/auth/logout", {
        method: "POST",
        credentials: "include",
      });
    } finally {
      setAuthenticatedAdmin(null);
      setStage("login");
      setStatus("Signed out");
      setSelectedInstall(null);
    }
  }

  async function loadSystem(report = true): Promise<void> {
    try {
      const data = await apiFetch<SystemSnapshot>("/v1/system/status", {
        method: "GET",
        credentials: "include",
      });
      setSystem(data);
      if (report) setStatus("System status refreshed");
    } catch (error) {
      setStatus(`System status failed: ${errorMessage(error)}`);
    }
  }

  async function loadInstallations(report = true): Promise<void> {
    try {
      const data = await apiFetch<{ items: Installation[] }>(
        "/v1/installations",
        {
          method: "GET",
          credentials: "include",
        },
      );
      setInstallations(data.items ?? []);
      if (report) setStatus(`Loaded ${data.items?.length ?? 0} installations`);
    } catch (error) {
      setStatus(`Load installations failed: ${errorMessage(error)}`);
    }
  }

  function updateOnboardingFromDomains(items: DomainRecord[]): void {
    if (items.length === 0) {
      setShowOnboardingWizard(true);
      setOnboardingStep(1);
      setLaunchAssistantStep(1);
      setView("launchAssistant");
      return;
    }

    const hasSSL = items.some(
      (item) =>
        item.tls?.status === "issued" ||
        item.tls?.status === "expiring" ||
        item.tls?.status === "pending",
    );

    if (!hasSSL) {
      setShowOnboardingWizard(true);
      setOnboardingStep(2);
      setLaunchAssistantStep(2);
      if (view === "onboarding" || view === "launchAssistant") {
        setView("launchAssistant");
        setStatus("Next step: issue SSL for your domain.");
      }
      return;
    }

    setShowOnboardingWizard(false);
    setOnboardingStep(3);
    setLaunchAssistantStep(3);
    if (view === "onboarding" || view === "launchAssistant") {
      setView("home");
      setStatus("Onboarding complete. PanelX is ready.");
    }
  }

  async function loadDomains(
    report = true,
    refreshHealth = false,
  ): Promise<DomainRecord[]> {
    try {
      const data = await apiFetch<{ items: DomainRecord[] }>(
        `/v1/domains${refreshHealth ? "?refreshHealth=true" : ""}`,
        {
          method: "GET",
          credentials: "include",
        },
      );
      const items = data.items ?? [];
      setDomains(items);
      if (report) setStatus(`Loaded ${items.length} domains`);
      return items;
    } catch (error) {
      setStatus(`Load domains failed: ${errorMessage(error)}`);
      return [];
    }
  }

  async function createDomain(): Promise<void> {
    const hostname = domainForm.hostname.trim();

    if (!hostname) {
      setStatus("Hostname is required");
      return;
    }
    if (!isLikelyDomainOrIP(hostname) || hostname.includes(" ")) {
      setStatus(
        "Use a valid hostname like example.com or blog.example.com (no spaces).",
      );
      return;
    }

    setStatus("Creating domain...");
    try {
      const created = await apiFetch<DomainRecord>("/v1/domains/create", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          hostname: domainForm.hostname.trim(),
          documentRoot: domainForm.documentRoot.trim(),
          ownerLabel: domainForm.ownerLabel.trim(),
          notes: domainForm.notes.trim(),
          enableNginx: domainForm.enableNginx,
        }),
      });

      setSelectedDomain(created);
      setRedirectForm({
        mode: created.redirects?.mode ?? "off",
        canonicalHost: created.redirects?.canonicalHost ?? "none",
        canonicalTarget: created.redirects?.canonicalTarget ?? "",
        customTargetUrl: created.redirects?.customTargetUrl ?? "",
        preservePath: created.redirects?.preservePath ?? true,
        preserveQuery: created.redirects?.preserveQuery ?? true,
        temporary: created.redirects?.temporary ?? false,
      });
      setDomainForm({
        hostname: "",
        documentRoot: "",
        ownerLabel: "",
        notes: "",
        enableNginx: true,
      });
      const items = await loadDomains(false, true);
      updateOnboardingFromDomains(items);
      setStatus(`Domain ${created.hostname} created`);
      pushToast(`Domain ${created.hostname} added`, "success");
    } catch (error) {
      const msg = `Create domain failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function updateDomainRedirects(id: string): Promise<void> {
    try {
      const updated = await apiFetch<DomainRecord>("/v1/domains/redirects", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id,
          mode: redirectForm.mode,
          canonicalHost: redirectForm.canonicalHost,
          canonicalTarget: redirectForm.canonicalTarget.trim(),
          customTargetUrl: redirectForm.customTargetUrl.trim(),
          preservePath: redirectForm.preservePath,
          preserveQuery: redirectForm.preserveQuery,
          temporary: redirectForm.temporary,
        }),
      });

      setDomains((prev) =>
        prev.map((d) => (d.id === updated.id ? updated : d)),
      );
      if (selectedDomain?.id === updated.id) {
        setSelectedDomain(updated);
      }
      setStatus(`Redirect policy updated for ${updated.hostname}`);
    } catch (error) {
      setStatus(`Update redirects failed: ${errorMessage(error)}`);
    }
  }

  function openDomainSite(domain: DomainRecord): void {
    const protocol = domain.tls?.enabled ? "https" : "http";
    window.open(
      `${protocol}://${domain.hostname}`,
      "_blank",
      "noopener,noreferrer",
    );
  }

  function openDomainAdmin(domain: DomainRecord): void {
    const protocol = domain.tls?.enabled ? "https" : "http";
    window.open(
      `${protocol}://${domain.hostname}/wp-admin`,
      "_blank",
      "noopener,noreferrer",
    );
  }

  async function copyDNSChecklist(domain: DomainRecord): Promise<void> {
    const checklist = [
      `Domain: ${domain.hostname}`,
      "1) Set A record to your VPS public IPv4",
      "2) Set AAAA record only if IPv6 is configured",
      "3) Wait for propagation and verify DNS resolution",
      "4) Ensure ports 80 and 443 are open",
      "5) Issue SSL from PanelX Domains tab",
      "6) Re-run health check after DNS propagation",
    ].join("\n");

    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(checklist);
      }
      setLastDNSChecklistCopiedFor(domain.hostname);
      setStatus(`DNS checklist copied for ${domain.hostname}`);
    } catch (error) {
      setStatus(`Copy checklist failed: ${errorMessage(error)}`);
    }
  }

  async function runDomainHealth(id?: string): Promise<void> {
    try {
      if (!id) {
        await loadDomains(false, true);
        setStatus("Domain health refreshed");
        return;
      }

      const updated = await apiFetch<DomainRecord>("/v1/domains/health", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });

      setDomains((prev) =>
        prev.map((d) => (d.id === updated.id ? updated : d)),
      );
      if (selectedDomain?.id === updated.id) {
        setSelectedDomain(updated);
      }
      setStatus(`Health updated for ${updated.hostname}`);
    } catch (error) {
      setStatus(`Domain health failed: ${errorMessage(error)}`);
    }
  }

  async function issueSSL(id: string): Promise<void> {
    if (!sslEmail.trim()) {
      setStatus("SSL email is required");
      return;
    }
    if (!isValidEmail(sslEmail)) {
      setStatus("Enter a valid SSL email address (example: admin@example.com).");
      return;
    }
    try {
      const updated = await apiFetch<DomainRecord>("/v1/domains/ssl/issue", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id,
          email: sslEmail.trim(),
          provider: "letsencrypt",
        }),
      });
      setDomains((prev) =>
        prev.map((d) => (d.id === updated.id ? updated : d)),
      );
      if (selectedDomain?.id === updated.id) {
        setSelectedDomain(updated);
      }
      setStatus(`SSL issued for ${updated.hostname}`);
      pushToast(`SSL issued for ${updated.hostname}`, "success");
    } catch (error) {
      const msg = `SSL issue failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function renewSSL(id: string): Promise<void> {
    try {
      const updated = await apiFetch<DomainRecord>("/v1/domains/ssl/renew", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      setDomains((prev) =>
        prev.map((d) => (d.id === updated.id ? updated : d)),
      );
      if (selectedDomain?.id === updated.id) {
        setSelectedDomain(updated);
      }
      setStatus(`SSL renewed for ${updated.hostname}`);
      pushToast(`SSL renewed for ${updated.hostname}`, "success");
    } catch (error) {
      const msg = `SSL renew failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function revokeSSL(id: string): Promise<void> {
    try {
      const updated = await apiFetch<DomainRecord>("/v1/domains/ssl/revoke", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id }),
      });
      setDomains((prev) =>
        prev.map((d) => (d.id === updated.id ? updated : d)),
      );
      if (selectedDomain?.id === updated.id) {
        setSelectedDomain(updated);
      }
      setStatus(`SSL revoked for ${updated.hostname}`);
      pushToast(`SSL revoked for ${updated.hostname}`, "success");
    } catch (error) {
      const msg = `SSL revoke failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function loadDomainLogs(domain: string): Promise<void> {
    if (!domain.trim()) {
      setStatus("Domain is required for logs");
      return;
    }
    try {
      const params = new URLSearchParams({
        domain: domain.trim(),
        type: domainLogsType,
        lines: String(Math.max(1, Math.min(5000, domainLogsLines || 200))),
      });
      const data = await apiFetch<{ lines: string[] }>(
        `/v1/domains/logs?${params.toString()}`,
        {
          method: "GET",
          credentials: "include",
        },
      );
      setDomainLogs(data.lines ?? []);
      setStatus(`Loaded ${data.lines?.length ?? 0} log lines for ${domain}`);
    } catch (error) {
      setStatus(`Load logs failed: ${errorMessage(error)}`);
    }
  }

  async function installWordPress(): Promise<void> {
    if (!installForm.domain.trim()) {
      setStatus("Domain or server IP is required");
      return;
    }
    if (!isLikelyDomainOrIP(installForm.domain)) {
      setStatus(
        "Enter a valid domain or IP. Example: example.com or 203.0.113.10",
      );
      return;
    }
    if (!installForm.adminEmail.trim()) {
      setStatus("Admin email is required");
      return;
    }
    if (!isValidEmail(installForm.adminEmail)) {
      setStatus("Enter a valid admin email address.");
      return;
    }

    setStatus("Provisioning WordPress...");
    try {
      const result = await apiFetch<Installation>("/v1/wordpress/install", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(installForm),
      });

      setSelectedInstall(result);
      setFileDomain(result.domain);
      setInstallForm((prev) => ({
        ...prev,
        siteTitle: "",
        adminUser: "",
        adminPassword: "",
        dbName: "",
        dbUser: "",
        dbPassword: "",
      }));
      await Promise.all([loadInstallations(false), loadSystem(false)]);
      setView("sites");
      setStatus(`WordPress installed at ${result.url}`);
      pushToast(`WordPress installed for ${result.domain}`, "success");
    } catch (error) {
      const msg = `Install failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function listFiles(nextPath?: string): Promise<void> {
    if (!fileDomain.trim()) {
      setStatus("File manager requires domain/IP");
      return;
    }

    const effectivePath =
      typeof nextPath === "string" ? nextPath : filePath.trim();

    setStatus("Loading file list...");
    try {
      const params = new URLSearchParams({
        domain: fileDomain.trim(),
        path: effectivePath,
      });
      const data = await apiFetch<{ entries: FileEntry[] }>(
        `/v1/files/list?${params.toString()}`,
        {
          method: "GET",
          credentials: "include",
        },
      );
      const loadedEntries = data.entries ?? [];
      const sortedEntries = [...loadedEntries].sort((a, b) => {
        if (a.isDir !== b.isDir) return a.isDir ? -1 : 1;
        return a.name.localeCompare(b.name, undefined, {
          sensitivity: "base",
          numeric: true,
        });
      });

      setEntries(sortedEntries);
      setFilePath(effectivePath);

      if (sortedEntries.length === 0) {
        setStatus(
          "This folder is empty. You can browse another path or create/upload files via your app deployment flow.",
        );
      } else {
        setStatus(
          `Loaded ${sortedEntries.length} items (folders first, then files). Select a file to preview or edit.`,
        );
      }
    } catch (error) {
      setStatus(`List files failed: ${errorMessage(error)}`);
    }
  }

  async function openFile(path: string): Promise<void> {
    try {
      const params = new URLSearchParams({
        domain: fileDomain.trim(),
        path,
      });
      const data = await apiFetch<{ content: string }>(
        `/v1/files/read?${params.toString()}`,
        {
          method: "GET",
          credentials: "include",
        },
      );
      setSelectedPath(path);
      setFileContent(data.content ?? "");
      setStatus(`Opened ${path}`);
    } catch (error) {
      setStatus(`Read failed: ${errorMessage(error)}`);
    }
  }

  async function saveFile(): Promise<void> {
    if (!selectedPath) {
      setStatus(
        "Select a file from the left panel first, then save your changes.",
      );
      return;
    }

    try {
      await apiFetch("/v1/files/write", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          domain: fileDomain.trim(),
          path: selectedPath,
          content: fileContent,
        }),
      });
      setStatus("File saved");
      pushToast("File saved successfully", "success");
    } catch (error) {
      const msg = `Save failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  async function deletePath(path: string): Promise<void> {
    if (!path.trim()) {
      setStatus("No path selected for deletion.");
      return;
    }

    try {
      await apiFetch("/v1/files/delete", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          domain: fileDomain.trim(),
          path,
        }),
      });
      if (selectedPath === path) {
        setSelectedPath("");
        setFileContent("");
      }
      setPendingDeletePath("");
      await listFiles();
      setStatus(`Deleted ${path}`);
      pushToast(`Deleted ${path}`, "success");
    } catch (error) {
      const msg = `Delete failed: ${errorMessage(error)}`;
      setStatus(msg);
      pushToast(msg, "error", 4200);
    }
  }

  if (stage === "loading") {
    return <CenteredShell colors={colors} title="PanelX" subtitle={status} />;
  }

  if (stage === "bootstrap") {
    return (
      <AuthShell
        colors={colors}
        title="First-Time Panel Setup"
        subtitle="Use installer API token once, then create your panel admin login."
      >
        <Field label="Installer API Token">
          <input
            style={inputStyle(colors)}
            type="password"
            value={setupForm.bootstrapToken}
            onChange={(e) =>
              setSetupForm((p) => ({ ...p, bootstrapToken: e.target.value }))
            }
            placeholder="Paste token printed by installer"
          />
        </Field>
        <Field label="Admin Username">
          <input
            style={inputStyle(colors)}
            value={setupForm.username}
            onChange={(e) =>
              setSetupForm((p) => ({ ...p, username: e.target.value }))
            }
            placeholder="admin"
          />
        </Field>
        <Field label="Admin Email">
          <input
            style={inputStyle(colors)}
            value={setupForm.email}
            onChange={(e) =>
              setSetupForm((p) => ({ ...p, email: e.target.value }))
            }
            placeholder="you@example.com"
          />
        </Field>
        <Field label="Password">
          <input
            style={inputStyle(colors)}
            type="password"
            value={setupForm.password}
            onChange={(e) =>
              setSetupForm((p) => ({ ...p, password: e.target.value }))
            }
          />
        </Field>
        <Field label="Confirm Password">
          <input
            style={inputStyle(colors)}
            type="password"
            value={setupForm.confirmPassword}
            onChange={(e) =>
              setSetupForm((p) => ({ ...p, confirmPassword: e.target.value }))
            }
          />
        </Field>

        <div style={{ display: "flex", gap: 10, marginTop: 10 }}>
          <button
            style={primaryButton(colors)}
            onClick={() => void handleSetup()}
          >
            Configure Panel
          </button>
          <ThemeToggle theme={theme} setTheme={setTheme} colors={colors} />
        </div>
        <StatusLine text={status} colors={colors} />
      </AuthShell>
    );
  }

  if (stage === "login") {
    return (
      <AuthShell
        colors={colors}
        title="Sign in to PanelX"
        subtitle="Use your panel admin username and password."
      >
        <Field label="Username">
          <input
            style={inputStyle(colors)}
            value={loginForm.username}
            onChange={(e) =>
              setLoginForm((p) => ({ ...p, username: e.target.value }))
            }
          />
        </Field>
        <Field label="Password">
          <input
            style={inputStyle(colors)}
            type="password"
            value={loginForm.password}
            onChange={(e) =>
              setLoginForm((p) => ({ ...p, password: e.target.value }))
            }
          />
        </Field>

        <div style={{ display: "flex", gap: 10, marginTop: 10 }}>
          <button
            style={primaryButton(colors)}
            onClick={() => void handleLogin()}
          >
            Sign In
          </button>
          <ThemeToggle theme={theme} setTheme={setTheme} colors={colors} />
        </div>
        <StatusLine text={status} colors={colors} />
      </AuthShell>
    );
  }

  return (
    <div
      style={{
        minHeight: "100vh",
        background: colors.bg,
        color: colors.text,
        fontFamily: "Inter, Segoe UI, Arial, sans-serif",
      }}
    >
      <header
        style={{
          minHeight: 72,
          borderBottom: `1px solid ${colors.borderSoft}`,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "12px 18px",
          backdropFilter: "blur(8px)",
          position: "sticky",
          top: 0,
          zIndex: 20,
          background: colors.panel,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <div style={logoBadge(colors)}>PX</div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 18 }}>PanelX</div>
            <div style={{ fontSize: 12, color: colors.textMuted }}>
              Control Center
            </div>
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ color: colors.textMuted, fontSize: 13 }}>
            Signed in as{" "}
            <strong style={{ color: colors.text }}>
              {authenticatedAdmin?.username ?? "admin"}
            </strong>
          </span>
          <button
            style={ghostButton(colors)}
            onClick={() =>
              void Promise.all([
                loadSystem(),
                loadInstallations(false),
                loadDomains(false),
              ])
            }
          >
            Refresh
          </button>
          <ThemeToggle theme={theme} setTheme={setTheme} colors={colors} />
          <button
            style={dangerButton(colors)}
            onClick={() => void handleLogout()}
          >
            Logout
          </button>
        </div>
      </header>

      <ToastStack
        colors={colors}
        toasts={toasts}
        onDismiss={dismissToast}
        isCompact={isCompact}
      />

      {isCompact && (
        <div
          style={{
            position: "sticky",
            top: 72,
            zIndex: 19,
            display: "grid",
            gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
            gap: 6,
            padding: "8px 10px",
            borderBottom: `1px solid ${colors.borderSoft}`,
            background: colors.panel,
            backdropFilter: "blur(8px)",
          }}
        >
          <button
            style={mobileQuickNavButtonStyle(
              colors,
              view === "home" || view === "dashboard",
            )}
            onClick={() => setView("home")}
          >
            Home
          </button>
          <button
            style={mobileQuickNavButtonStyle(colors, view === "launchAssistant")}
            onClick={() => setView("launchAssistant")}
          >
            Launch
          </button>
          <button
            style={mobileQuickNavButtonStyle(colors, view === "sites")}
            onClick={() => setView("sites")}
          >
            Sites
          </button>
          <button
            style={mobileQuickNavButtonStyle(colors, view === "files")}
            onClick={() => setView("files")}
          >
            Files
          </button>
          <button
            style={mobileQuickNavButtonStyle(colors, view === "help")}
            onClick={() => setView("help")}
          >
            Help
          </button>
        </div>
      )}

      <div
        style={{
          display: "grid",
          gridTemplateColumns: isCompact
            ? "1fr"
            : "minmax(220px, 260px) minmax(0, 1fr)",
          minHeight: "calc(100vh - 72px)",
        }}
      >
        <aside
          style={{
            borderRight: isCompact ? "none" : `1px solid ${colors.borderSoft}`,
            borderBottom: isCompact ? `1px solid ${colors.borderSoft}` : "none",
            padding: 14,
            background: colors.panelAlt,
            boxShadow: colors.inset,
            position: isCompact ? "static" : "sticky",
            top: 72,
            height: isCompact ? "auto" : "calc(100vh - 72px)",
            overflowY: "auto",
          }}
        >
          <div
            style={{
              fontSize: 11,
              textTransform: "uppercase",
              letterSpacing: 0.4,
              color: colors.textMuted,
              marginBottom: 8,
              fontWeight: 700,
            }}
          >
            Main
          </div>

          <NavItem
            colors={colors}
            active={view === "home" || view === "dashboard"}
            onClick={() => setView("home")}
            icon="🏠"
            label="Home"
          />
          <NavItem
            colors={colors}
            active={view === "launchAssistant"}
            onClick={() => setView("launchAssistant")}
            icon="🧭"
            label="Launch Site"
          />
          <NavItem
            colors={colors}
            active={view === "sites"}
            onClick={() => setView("sites")}
            icon="🗂️"
            label="Sites"
          />
          <NavItem
            colors={colors}
            active={view === "files"}
            onClick={() => setView("files")}
            icon="📁"
            label="Files"
          />
          <NavItem
            colors={colors}
            active={view === "help"}
            onClick={() => setView("help")}
            icon="❓"
            label="Help"
          />

          <div
            style={{
              marginTop: 12,
              marginBottom: 8,
              padding: 10,
              borderRadius: 10,
              border: `1px solid ${colors.borderSoft}`,
              background: colors.panel,
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              gap: 8,
            }}
          >
            <div>
              <div style={{ fontWeight: 700, fontSize: 12 }}>
                Advanced tools
              </div>
              <div style={{ fontSize: 11, color: colors.textMuted }}>
                Show technical sections
              </div>
            </div>
            <label
              style={{
                display: "flex",
                alignItems: "center",
                gap: 6,
                fontSize: 12,
                color: colors.textMuted,
              }}
            >
              <input
                type="checkbox"
                checked={!beginnerMode}
                onChange={(e) => setBeginnerMode(!e.target.checked)}
              />
              {beginnerMode ? "Off" : "On"}
            </label>
          </div>

          {!beginnerMode && (
            <>
              <div
                style={{
                  fontSize: 11,
                  textTransform: "uppercase",
                  letterSpacing: 0.4,
                  color: colors.textMuted,
                  marginBottom: 8,
                  marginTop: 2,
                  fontWeight: 700,
                }}
              >
                Advanced
              </div>
              <NavItem
                colors={colors}
                active={view === "domains"}
                onClick={() => setView("domains")}
                icon="🌍"
                label="Domains"
              />
              <NavItem
                colors={colors}
                active={view === "wordpress"}
                onClick={() => setView("wordpress")}
                icon="🚀"
                label="WordPress (Raw)"
              />
              <NavItem
                colors={colors}
                active={view === "domainLogs"}
                onClick={() => setView("domainLogs")}
                icon="📜"
                label="Domain Logs"
              />
              <NavItem
                colors={colors}
                active={view === "system"}
                onClick={() => setView("system")}
                icon="🖥️"
                label="System"
              />
            </>
          )}

          <div style={{ marginTop: 20, fontSize: 12, color: colors.textMuted }}>
            <div style={{ marginBottom: 8, fontWeight: 600 }}>Auto Refresh</div>
            <label style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <input
                type="checkbox"
                checked={autoRefresh}
                onChange={(e) => setAutoRefresh(e.target.checked)}
              />
              Enabled
            </label>
            <input
              style={{ ...inputStyle(colors), marginTop: 8 }}
              type="number"
              min={5}
              value={refreshSeconds}
              onChange={(e) => setRefreshSeconds(Number(e.target.value || 15))}
            />
          </div>

          <div style={{ marginTop: 18, fontSize: 12, color: colors.textMuted }}>
            <div>Admin Email</div>
            <div style={{ color: colors.text }}>
              {authenticatedAdmin?.email ?? "-"}
            </div>
          </div>
        </aside>

        <main
          style={{ padding: isCompact ? 12 : 18, display: "grid", gap: 14 }}
        >
          <StatusLine text={status} colors={colors} />

          {(view === "onboarding" || view === "launchAssistant") && (
            <LaunchAssistantPanel
              colors={colors}
              onboardingSummary={onboardingSummary}
              launchAssistantProgress={launchAssistantProgress}
              launchAssistantStep={launchAssistantStep}
              setLaunchAssistantStep={setLaunchAssistantStep}
              launchAssistantDomain={launchAssistantDomain}
              setLaunchAssistantDomain={setLaunchAssistantDomain}
              selectedLaunchDomain={selectedLaunchDomain}
              showOnboardingWizard={showOnboardingWizard}
              onGoToAddDomain={() => {
                setView("domains");
              }}
              onGoToConfigureSSL={() => {
                if (selectedLaunchDomain) {
                  setSelectedDomain(selectedLaunchDomain);
                  setView("domains");
                }
              }}
              onGoToInstallWordPress={() => {
                if (selectedLaunchDomain) {
                  setInstallForm((prev) => ({
                    ...prev,
                    domain: selectedLaunchDomain.hostname,
                    adminEmail:
                      prev.adminEmail || authenticatedAdmin?.email || "",
                  }));
                  setView("wordpress");
                }
              }}
              onOpenSite={() => {
                if (selectedLaunchDomain) {
                  openDomainSite(selectedLaunchDomain);
                }
              }}
              onCheckDomainHealth={() => {
                if (selectedLaunchDomain) {
                  void runDomainHealth(selectedLaunchDomain.id);
                }
              }}
              onCopyDNSChecklist={() => {
                if (selectedLaunchDomain) {
                  void copyDNSChecklist(selectedLaunchDomain);
                }
              }}
              onOpenWpAdmin={() => {
                if (selectedLaunchDomain) {
                  openDomainAdmin(selectedLaunchDomain);
                }
              }}
              onOpenFiles={() => {
                if (selectedLaunchDomain) {
                  setFileDomain(selectedLaunchDomain.hostname);
                  setFilePath("/public_html");
                  setView("files");
                }
              }}
            />
          )}

          {view === "help" && (
            <HelpPanel
              colors={colors}
              onOpenLaunchAssistant={() => setView("launchAssistant")}
              onOpenFiles={() => setView("files")}
              onBackHome={() => setView("home")}
            />
          )}

          {(view === "home" || view === "system" || view === "dashboard") && (
            <>
              {(view === "home" || view === "dashboard") && (
                <section style={panelStyle(colors)}>
                  <h3 style={sectionTitle}>Beginner Next Action</h3>
                  <p style={{ marginTop: 0, color: colors.textMuted }}>
                    Follow the recommended next step to move from server setup to a live site.
                  </p>
                  <div style={gridCards(3)}>
                    <Metric
                      colors={colors}
                      label="Progress"
                      value={`${launchAssistantProgress.completedSteps}/${launchAssistantProgress.totalSteps}`}
                      sub="Launch checklist"
                    />
                    <Metric
                      colors={colors}
                      label="Next Step"
                      value={launchAssistantProgress.nextStep === 4 ? "Complete" : `Step ${launchAssistantProgress.nextStep}`}
                      sub={launchAssistantProgress.ctaLabel}
                    />
                    <Metric
                      colors={colors}
                      label="Working Domain"
                      value={selectedLaunchDomain?.hostname || "Not selected"}
                      sub={selectedLaunchDomain ? "Ready for guided actions" : "Choose or add a domain first"}
                    />
                  </div>
                  <div
                    style={{
                      marginTop: 10,
                      display: "flex",
                      gap: 8,
                      flexWrap: "wrap",
                    }}
                  >
                    <button
                      style={primaryButton(colors)}
                      onClick={() => setView("launchAssistant")}
                    >
                      Open Launch Assistant
                    </button>
                    <button
                      style={ghostButton(colors)}
                      onClick={() => setView("domains")}
                    >
                      Manage Domains
                    </button>
                    <button
                      style={ghostButton(colors)}
                      onClick={() => setView("wordpress")}
                    >
                      Install WordPress
                    </button>
                    <button
                      style={ghostButton(colors)}
                      disabled={!selectedLaunchDomain}
                      onClick={() => {
                        if (selectedLaunchDomain) {
                          openDomainSite(selectedLaunchDomain);
                        }
                      }}
                    >
                      Open Site
                    </button>
                  </div>
                </section>
              )}

              {view === "system" && (
                <section style={panelStyle(colors)}>
                  <h3 style={sectionTitle}>System Monitoring</h3>
                  <p style={{ marginTop: 0, color: colors.textMuted }}>
                    This section is focused on technical server health, services, resource usage, and diagnostics.
                  </p>
                  <div style={gridCards(3)}>
                    <Metric
                      colors={colors}
                      label="Hostname"
                      value={system?.hostname || "—"}
                      sub={`${system?.os || "linux"} ${system?.arch || ""}`}
                    />
                    <Metric
                      colors={colors}
                      label="Health Snapshot"
                      value={system?.status || "unknown"}
                      sub={timeAgo(system?.timestamp)}
                    />
                    <Metric
                      colors={colors}
                      label="Services"
                      value={`${(system?.services ?? []).filter((s) => s.active).length}/${(system?.services ?? []).length}`}
                      sub="active / total"
                    />
                  </div>
                  <div style={{ marginTop: 10, display: "flex", gap: 8, flexWrap: "wrap" }}>
                    <button
                      style={ghostButton(colors)}
                      onClick={() =>
                        void Promise.all([
                          loadSystem(),
                          loadInstallations(false),
                          loadDomains(false),
                        ])
                      }
                    >
                      Refresh System Data
                    </button>
                    <button
                      style={ghostButton(colors)}
                      onClick={() => setView("domainLogs")}
                    >
                      Open Domain Logs
                    </button>
                    <button
                      style={ghostButton(colors)}
                      onClick={() => setView("home")}
                    >
                      Back to Home
                    </button>
                  </div>
                </section>
              )}


              <div style={gridCards(4)}>
                <Metric
                  colors={colors}
                  label="Host"
                  value={system?.hostname || "—"}
                  sub={`${system?.os || "linux"} ${system?.arch || ""}`}
                />
                <Metric
                  colors={colors}
                  label="Uptime"
                  value={system?.uptime?.human || "—"}
                  sub={timeAgo(system?.timestamp)}
                />
                <Metric
                  colors={colors}
                  label="CPU"
                  value={`${system?.cpu?.usagePercent ?? 0}%`}
                  sub={`${system?.cpu?.cores ?? 0} cores`}
                />
                <Metric
                  colors={colors}
                  label="Memory"
                  value={`${system?.memory?.usedPercent ?? 0}%`}
                  sub={`${formatBytes(system?.memory?.usedBytes || 0)} / ${formatBytes(system?.memory?.totalBytes || 0)}`}
                />
                <Metric
                  colors={colors}
                  label="Load"
                  value={`${system?.load?.one ?? 0} / ${system?.load?.five ?? 0} / ${system?.load?.fifteen ?? 0}`}
                  sub="1m / 5m / 15m"
                />
                <Metric
                  colors={colors}
                  label="Sites Detected"
                  value={`${system?.wordpress?.detectedSites ?? 0}`}
                  sub={system?.wordpress?.sitesRoot || ""}
                />
                <Metric
                  colors={colors}
                  label="Install Registry"
                  value={
                    system?.wordpress?.installStoreOk ? "Ready" : "Missing"
                  }
                  sub=".panelx/installations.json"
                />
                <Metric
                  colors={colors}
                  label="PHP Socket"
                  value={
                    system?.wordpress?.phpSocketFound ? "Detected" : "Not Found"
                  }
                  sub="FPM runtime status"
                />
              </div>

              <section style={panelStyle(colors)}>
                <h3 style={sectionTitle}>Service Health</h3>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(auto-fit, minmax(230px,1fr))",
                    gap: 8,
                  }}
                >
                  {(system?.services ?? []).map((s) => (
                    <div key={s.name} style={serviceCard(colors, s.active)}>
                      <div>
                        <div style={{ fontWeight: 700 }}>{s.name}</div>
                        <div style={{ fontSize: 12, color: colors.textMuted }}>
                          {s.description || s.state}
                        </div>
                      </div>
                      <span
                        style={{
                          fontSize: 12,
                          fontWeight: 700,
                          color: s.active ? colors.success : colors.danger,
                        }}
                      >
                        {s.state}
                      </span>
                    </div>
                  ))}
                </div>
              </section>
            </>
          )}

          {view === "wordpress" && (
            <section style={panelStyle(colors)}>
              <h3 style={sectionTitle}>One-Click WordPress Installer</h3>
              <p style={{ marginTop: 0, color: colors.textMuted }}>
                Enter domain or server IP and admin email. PanelX can
                auto-generate admin/database credentials if left blank.
              </p>
              <div style={gridCards(3)}>
                <Field label="Domain or IP">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.domain}
                    onChange={(e) =>
                      setInstallForm((p) => ({ ...p, domain: e.target.value }))
                    }
                    placeholder="example.com or 203.0.113.10"
                  />
                  {installForm.domain.trim() &&
                    !isLikelyDomainOrIP(installForm.domain) && (
                      <small style={{ color: colors.danger }}>
                        Enter a valid domain or IPv4 address.
                      </small>
                    )}
                </Field>
                <Field label="Install Path">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.installPath}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        installPath: e.target.value,
                      }))
                    }
                    placeholder="/ or /blog"
                  />
                </Field>
                <Field label="Admin Email (required)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.adminEmail}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        adminEmail: e.target.value,
                      }))
                    }
                    placeholder="owner@example.com"
                  />
                  {installForm.adminEmail.trim() &&
                    !isValidEmail(installForm.adminEmail) && (
                      <small style={{ color: colors.danger }}>
                        Use a valid email format like name@example.com.
                      </small>
                    )}
                </Field>
                <Field label="Site Title (optional)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.siteTitle}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        siteTitle: e.target.value,
                      }))
                    }
                  />
                </Field>
                <Field label="Admin Username (optional)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.adminUser}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        adminUser: e.target.value,
                      }))
                    }
                  />
                </Field>
                <Field label="Admin Password (optional)">
                  <input
                    style={inputStyle(colors)}
                    type="password"
                    value={installForm.adminPassword}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        adminPassword: e.target.value,
                      }))
                    }
                  />
                </Field>
                <Field label="DB Name (optional)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.dbName}
                    onChange={(e) =>
                      setInstallForm((p) => ({ ...p, dbName: e.target.value }))
                    }
                  />
                </Field>
                <Field label="DB User (optional)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.dbUser}
                    onChange={(e) =>
                      setInstallForm((p) => ({ ...p, dbUser: e.target.value }))
                    }
                  />
                </Field>
                <Field label="DB Password (optional)">
                  <input
                    style={inputStyle(colors)}
                    value={installForm.dbPassword}
                    onChange={(e) =>
                      setInstallForm((p) => ({
                        ...p,
                        dbPassword: e.target.value,
                      }))
                    }
                  />
                </Field>
              </div>
              <div style={{ marginTop: 10, display: "flex", gap: 10 }}>
                <button
                  style={primaryButton(colors)}
                  onClick={() => void installWordPress()}
                  disabled={
                    !isLikelyDomainOrIP(installForm.domain) ||
                    !isValidEmail(installForm.adminEmail)
                  }
                >
                  Install WordPress
                </button>
                <button
                  style={ghostButton(colors)}
                  onClick={() => setView("sites")}
                >
                  View Sites
                </button>
              </div>
            </section>
          )}

          {view === "sites" && (
            <SitesPanel
              colors={colors}
              isCompact={isCompact}
              panelStyle={panelStyle}
              gridCards={gridCards}
              ghostButton={ghostButton}
              primaryButton={primaryButton}
              installations={installations}
              selectedInstall={selectedInstall}
              setSelectedInstall={setSelectedInstall}
              setFileDomain={setFileDomain}
              setFilePath={setFilePath}
              setView={setView}
              loadInstallations={loadInstallations}
            />
          )}

          {view === "domains" && (
            <section style={panelStyle(colors)}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  gap: 10,
                  marginBottom: 10,
                }}
              >
                <h3 style={sectionTitle}>Domain Management</h3>
                <div style={{ display: "flex", gap: 8 }}>
                  <button
                    style={ghostButton(colors)}
                    onClick={() => void loadDomains(true, false)}
                  >
                    Reload
                  </button>
                  <button
                    style={ghostButton(colors)}
                    onClick={() => void runDomainHealth()}
                  >
                    Refresh Health
                  </button>
                </div>
              </div>

              <div style={{ ...panelStyle(colors), marginBottom: 12 }}>
                <h4 style={{ marginTop: 0 }}>Add Domain</h4>
                <div style={gridCards(2)}>
                  <Field label="Hostname">
                    <input
                      style={inputStyle(colors)}
                      value={domainForm.hostname}
                      onChange={(e) =>
                        setDomainForm((p) => ({
                          ...p,
                          hostname: e.target.value,
                        }))
                      }
                      placeholder="example.com or blog.example.com"
                    />
                    {domainForm.hostname.trim() &&
                      !isLikelyDomainOrIP(domainForm.hostname) && (
                        <small style={{ color: colors.danger }}>
                          Hostname looks invalid. Use a domain like example.com.
                        </small>
                      )}
                  </Field>
                  <Field label="Document Root (optional)">
                    <input
                      style={inputStyle(colors)}
                      value={domainForm.documentRoot}
                      onChange={(e) =>
                        setDomainForm((p) => ({
                          ...p,
                          documentRoot: e.target.value,
                        }))
                      }
                      placeholder="/var/www/panelx/sites/example.com/public_html"
                    />
                  </Field>
                  <Field label="Owner Label (optional)">
                    <input
                      style={inputStyle(colors)}
                      value={domainForm.ownerLabel}
                      onChange={(e) =>
                        setDomainForm((p) => ({
                          ...p,
                          ownerLabel: e.target.value,
                        }))
                      }
                      placeholder="Client A"
                    />
                  </Field>
                  <Field label="Notes (optional)">
                    <input
                      style={inputStyle(colors)}
                      value={domainForm.notes}
                      onChange={(e) =>
                        setDomainForm((p) => ({ ...p, notes: e.target.value }))
                      }
                      placeholder="Primary marketing website"
                    />
                  </Field>
                </div>
                <label
                  style={{ display: "flex", gap: 8, alignItems: "center" }}
                >
                  <input
                    type="checkbox"
                    checked={domainForm.enableNginx}
                    onChange={(e) =>
                      setDomainForm((p) => ({
                        ...p,
                        enableNginx: e.target.checked,
                      }))
                    }
                  />
                  Enable and sync Nginx config
                </label>
                <div style={{ marginTop: 8 }}>
                  <button
                    style={primaryButton(colors)}
                    onClick={() => void createDomain()}
                  >
                    Add Domain
                  </button>
                </div>
              </div>

              <div
                style={{
                  overflowX: "auto",
                  border: `1px solid ${colors.borderSoft}`,
                  borderRadius: 12,
                  background: colors.panelAlt,
                }}
              >
                <table style={{ width: "100%", borderCollapse: "collapse" }}>
                  <thead>
                    <tr>
                      {[
                        "Hostname",
                        "Document Root",
                        "DNS",
                        "Nginx",
                        "SSL",
                        "Status",
                        "Actions",
                      ].map((h) => (
                        <th key={h} style={tableHeader(colors)}>
                          {h}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {domains.map((d) => (
                      <tr key={d.id}>
                        <td style={tableCell(colors)}>
                          <strong>{d.hostname}</strong>
                          <div
                            style={{ fontSize: 12, color: colors.textMuted }}
                          >
                            {d.isSubdomain
                              ? `Subdomain of ${d.rootDomain}`
                              : "Root domain"}
                          </div>
                        </td>
                        <td style={tableCell(colors)}>{d.documentRoot}</td>
                        <td style={tableCell(colors)}>
                          {d.health?.resolvesToServerIp
                            ? "Matches"
                            : "Mismatch"}
                        </td>
                        <td style={tableCell(colors)}>
                          {d.health?.nginxConfigPresent &&
                          d.health?.nginxEnabled
                            ? "Enabled"
                            : "Missing"}
                        </td>
                        <td style={tableCell(colors)}>
                          {d.tls?.status || "none"}
                        </td>
                        <td style={tableCell(colors)}>{d.status}</td>
                        <td style={tableCell(colors)}>
                          <div
                            style={{
                              display: "flex",
                              gap: 6,
                              flexWrap: "wrap",
                            }}
                          >
                            <button
                              style={ghostButton(colors)}
                              onClick={() => {
                                setSelectedDomain(d);
                                setFileDomain(d.hostname);
                              }}
                            >
                              Select
                            </button>
                            <button
                              style={ghostButton(colors)}
                              onClick={() => void runDomainHealth(d.id)}
                            >
                              Health
                            </button>
                            <button
                              style={ghostButton(colors)}
                              onClick={() => void loadDomainLogs(d.hostname)}
                            >
                              Logs
                            </button>
                            <button
                              style={ghostButton(colors)}
                              onClick={() => openDomainSite(d)}
                            >
                              Open Site
                            </button>
                            <button
                              style={ghostButton(colors)}
                              onClick={() => openDomainAdmin(d)}
                            >
                              WP Admin
                            </button>
                            <button
                              style={ghostButton(colors)}
                              onClick={() => void copyDNSChecklist(d)}
                            >
                              Copy DNS
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                    {domains.length === 0 && (
                      <tr>
                        <td style={tableCell(colors)} colSpan={7}>
                          No domains found.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {selectedDomain && (
                <div style={{ ...panelStyle(colors), marginTop: 12 }}>
                  <h4 style={{ marginTop: 0 }}>
                    SSL & Health: {selectedDomain.hostname}
                  </h4>
                  <div style={gridCards(3)}>
                    <CredentialItem
                      label="SSL Status"
                      value={selectedDomain.tls?.status || "none"}
                      colors={colors}
                    />
                    <CredentialItem
                      label="Issued At"
                      value={
                        selectedDomain.tls?.issuedAt
                          ? new Date(
                              selectedDomain.tls.issuedAt,
                            ).toLocaleString()
                          : "-"
                      }
                      colors={colors}
                    />
                    <CredentialItem
                      label="Expires At"
                      value={
                        selectedDomain.tls?.expiresAt
                          ? new Date(
                              selectedDomain.tls.expiresAt,
                            ).toLocaleString()
                          : "-"
                      }
                      colors={colors}
                    />
                  </div>

                  <div
                    style={{
                      display: "flex",
                      gap: 8,
                      marginTop: 10,
                      flexWrap: "wrap",
                    }}
                  >
                    <div style={{ display: "grid", gap: 6 }}>
                      <input
                        style={{ ...inputStyle(colors), maxWidth: 340 }}
                        value={sslEmail}
                        onChange={(e) => setSslEmail(e.target.value)}
                        placeholder="SSL email for Let's Encrypt"
                      />
                      {sslEmail.trim() && !isValidEmail(sslEmail) && (
                        <small style={{ color: colors.danger }}>
                          Enter a valid SSL email (used by Let's Encrypt).
                        </small>
                      )}
                    </div>
                    <button
                      style={primaryButton(colors)}
                      onClick={() => void issueSSL(selectedDomain.id)}
                      disabled={!isValidEmail(sslEmail)}
                    >
                      Issue SSL
                    </button>
                    <button
                      style={ghostButton(colors)}
                      onClick={() => void renewSSL(selectedDomain.id)}
                    >
                      Renew SSL
                    </button>
                    <button
                      style={dangerButton(colors)}
                      onClick={() => void revokeSSL(selectedDomain.id)}
                    >
                      Revoke SSL
                    </button>
                  </div>

                  <div style={{ marginTop: 12 }}>
                    <h5 style={{ margin: "0 0 8px 0" }}>
                      Redirect & Canonical
                    </h5>
                    <div style={gridCards(3)}>
                      <Field label="Redirect Mode">
                        <select
                          style={inputStyle(colors)}
                          value={redirectForm.mode}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              mode: e.target
                                .value as DomainRedirectForm["mode"],
                            }))
                          }
                        >
                          <option value="off">off</option>
                          <option value="http_to_https">http_to_https</option>
                          <option value="custom">custom</option>
                        </select>
                      </Field>
                      <Field label="Canonical Host">
                        <select
                          style={inputStyle(colors)}
                          value={redirectForm.canonicalHost}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              canonicalHost: e.target
                                .value as DomainRedirectForm["canonicalHost"],
                            }))
                          }
                        >
                          <option value="none">none</option>
                          <option value="root">root</option>
                          <option value="www">www</option>
                          <option value="custom">custom</option>
                        </select>
                      </Field>
                      <Field label="Canonical Target (if custom)">
                        <input
                          style={inputStyle(colors)}
                          value={redirectForm.canonicalTarget}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              canonicalTarget: e.target.value,
                            }))
                          }
                          placeholder="canonical.example.com"
                        />
                      </Field>
                      <Field label="Custom Redirect URL (if mode=custom)">
                        <input
                          style={inputStyle(colors)}
                          value={redirectForm.customTargetUrl}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              customTargetUrl: e.target.value,
                            }))
                          }
                          placeholder="https://destination.example.com"
                        />
                      </Field>
                    </div>
                    <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
                      <label
                        style={{
                          display: "flex",
                          gap: 8,
                          alignItems: "center",
                        }}
                      >
                        <input
                          type="checkbox"
                          checked={redirectForm.preservePath}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              preservePath: e.target.checked,
                            }))
                          }
                        />
                        Preserve path
                      </label>
                      <label
                        style={{
                          display: "flex",
                          gap: 8,
                          alignItems: "center",
                        }}
                      >
                        <input
                          type="checkbox"
                          checked={redirectForm.preserveQuery}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              preserveQuery: e.target.checked,
                            }))
                          }
                        />
                        Preserve query
                      </label>
                      <label
                        style={{
                          display: "flex",
                          gap: 8,
                          alignItems: "center",
                        }}
                      >
                        <input
                          type="checkbox"
                          checked={redirectForm.temporary}
                          onChange={(e) =>
                            setRedirectForm((p) => ({
                              ...p,
                              temporary: e.target.checked,
                            }))
                          }
                        />
                        Temporary redirect
                      </label>
                      <button
                        style={primaryButton(colors)}
                        onClick={() =>
                          void updateDomainRedirects(selectedDomain.id)
                        }
                      >
                        Save Redirect Policy
                      </button>
                    </div>
                  </div>

                  {lastDNSChecklistCopiedFor === selectedDomain.hostname && (
                    <p style={{ marginTop: 8, color: colors.textMuted }}>
                      DNS checklist copied for {selectedDomain.hostname}.
                    </p>
                  )}

                  {selectedDomain.health?.warnings &&
                    selectedDomain.health.warnings.length > 0 && (
                      <div style={{ marginTop: 10 }}>
                        <strong>Health Warnings</strong>
                        <ul style={{ marginTop: 6, color: colors.textMuted }}>
                          {selectedDomain.health.warnings.map(
                            (warning, idx) => (
                              <li key={idx}>{warning}</li>
                            ),
                          )}
                        </ul>
                      </div>
                    )}
                </div>
              )}
            </section>
          )}

          {view === "domainLogs" && (
            <section style={panelStyle(colors)}>
              <h3 style={sectionTitle}>Domain Logs</h3>
              <div
                style={{
                  display: "flex",
                  gap: 8,
                  flexWrap: "wrap",
                  alignItems: "center",
                  marginBottom: 8,
                }}
              >
                <input
                  style={{ ...inputStyle(colors), minWidth: 260 }}
                  value={fileDomain}
                  onChange={(e) => setFileDomain(e.target.value)}
                  placeholder="domain (example.com)"
                />
                <select
                  style={{ ...inputStyle(colors), width: 140 }}
                  value={domainLogsType}
                  onChange={(e) =>
                    setDomainLogsType(e.target.value as "access" | "error")
                  }
                >
                  <option value="access">access</option>
                  <option value="error">error</option>
                </select>
                <input
                  style={{ ...inputStyle(colors), width: 130 }}
                  type="number"
                  min={1}
                  max={5000}
                  value={domainLogsLines}
                  onChange={(e) =>
                    setDomainLogsLines(Number(e.target.value || 200))
                  }
                />
                <button
                  style={primaryButton(colors)}
                  onClick={() => void loadDomainLogs(fileDomain)}
                >
                  Load Logs
                </button>
              </div>
              <div style={filePane(colors)}>
                <pre
                  style={{
                    margin: 0,
                    whiteSpace: "pre-wrap",
                    wordBreak: "break-word",
                    fontFamily:
                      "ui-monospace, SFMono-Regular, Menlo, monospace",
                    fontSize: 12,
                    lineHeight: 1.5,
                    color: colors.text,
                  }}
                >
                  {domainLogs.length > 0
                    ? domainLogs.join("\n")
                    : "No logs loaded yet."}
                </pre>
              </div>
            </section>
          )}

          {view === "files" && (
            <FilesPanel
              colors={colors}
              isCompact={isCompact}
              panelStyle={panelStyle}
              inputStyle={inputStyle}
              primaryButton={primaryButton}
              ghostButton={ghostButton}
              dangerButton={dangerButton}
              fileDomain={fileDomain}
              filePath={filePath}
              entries={entries}
              selectedPath={selectedPath}
              fileContent={fileContent}
              pendingDeletePath={pendingDeletePath}
              fileQuickPaths={fileQuickPaths}
              fileBreadcrumbs={fileBreadcrumbs}
              setFileDomain={setFileDomain}
              setFilePath={setFilePath}
              setFileContent={setFileContent}
              setPendingDeletePath={setPendingDeletePath}
              listFiles={listFiles}
              openFile={openFile}
              saveFile={saveFile}
              deletePath={deletePath}
            />
          )}
        </main>
      </div>
    </div>
  );
}

function CenteredShell(props: {
  colors: ThemeTokens;
  title: string;
  subtitle: string;
}) {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: props.colors.bg,
        display: "grid",
        placeItems: "center",
      }}
    >
      <div
        style={{
          ...panelStyle(props.colors),
          width: "min(92vw, 520px)",
          textAlign: "center",
          padding: 22,
        }}
      >
        <h1 style={{ marginTop: 0 }}>{props.title}</h1>
        <p style={{ color: props.colors.textMuted, marginBottom: 0 }}>
          {props.subtitle}
        </p>
      </div>
    </div>
  );
}

function AuthShell(props: {
  colors: ThemeTokens;
  title: string;
  subtitle: string;
  children: React.ReactNode;
}) {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: props.colors.bg,
        display: "grid",
        placeItems: "center",
        padding: 16,
      }}
    >
      <div
        style={{
          ...panelStyle(props.colors),
          width: "min(94vw, 560px)",
          padding: 20,
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: 6,
          }}
        >
          <div style={logoBadge(props.colors)}>PX</div>
          <div>
            <h2 style={{ margin: 0 }}>{props.title}</h2>
            <p style={{ margin: 0, color: props.colors.textMuted }}>
              {props.subtitle}
            </p>
          </div>
        </div>
        <div style={{ marginTop: 14 }}>{props.children}</div>
      </div>
    </div>
  );
}

function Field(props: { label: string; children: React.ReactNode }) {
  return (
    <label style={{ display: "grid", gap: 6, marginBottom: 8, fontSize: 14 }}>
      <span>{props.label}</span>
      {props.children}
    </label>
  );
}

function StatusLine(props: { text: string; colors: ThemeTokens }) {
  const lowered = props.text.toLowerCase();
  const isError = lowered.includes("failed") || lowered.includes("error");
  const isSuccess =
    lowered.includes("ready") ||
    lowered.includes("welcome") ||
    lowered.includes("signed in") ||
    lowered.includes("complete");

  return (
    <div
      style={{
        border: `1px solid ${
          isError
            ? "rgba(239,68,68,0.4)"
            : isSuccess
              ? "rgba(34,197,94,0.35)"
              : props.colors.borderSoft
        }`,
        borderRadius: 10,
        padding: "9px 12px",
        color: isError
          ? props.colors.danger
          : isSuccess
            ? props.colors.success
            : props.colors.textMuted,
        background: props.colors.panelAlt,
        boxShadow: props.colors.inset,
        fontWeight: 500,
      }}
    >
      {props.text}
    </div>
  );
}

function ThemeToggle(props: {
  theme: ThemeMode;
  setTheme: (t: ThemeMode) => void;
  colors: ThemeTokens;
}) {
  return (
    <button
      style={ghostButton(props.colors)}
      onClick={() => props.setTheme(props.theme === "light" ? "dark" : "light")}
    >
      {props.theme === "light" ? "🌙 Dark" : "☀️ Light"}
    </button>
  );
}

function NavItem(props: {
  colors: ThemeTokens;
  active: boolean;
  icon: string;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={props.onClick}
      style={{
        width: "100%",
        textAlign: "left",
        marginBottom: 6,
        borderRadius: 10,
        border: `1px solid ${props.active ? props.colors.primary : props.colors.borderSoft}`,
        background: props.active
          ? props.colors.primarySoft
          : props.colors.panel,
        color: props.colors.text,
        padding: "10px 12px",
        cursor: "pointer",
        fontWeight: props.active ? 700 : 500,
      }}
    >
      {props.icon} {props.label}
    </button>
  );
}







function buildOnboardingSummary(
  domains: DomainRecord[],
  installations: Installation[],
): { summary: string; nextStep: string; ready: boolean } {
  const hasDomain = domains.length > 0;
  const hasSSL = domains.some(
    (d) => d.tls?.status === "issued" || d.tls?.status === "expiring",
  );
  const hasWordPress = installations.length > 0;

  if (!hasDomain) {
    return {
      summary: "No managed domain yet. Start by adding your first domain.",
      nextStep: "Add your first domain",
      ready: false,
    };
  }

  if (!hasSSL) {
    return {
      summary:
        "Domain added, but HTTPS is not ready yet. Issue an SSL certificate next.",
      nextStep: "Issue SSL for your domain",
      ready: false,
    };
  }

  if (!hasWordPress) {
    return {
      summary:
        "Domain and SSL look good. Install WordPress to complete launch setup.",
      nextStep: "Run one-click WordPress install",
      ready: false,
    };
  }

  return {
    summary:
      "Domain, SSL, and WordPress are all configured. Your site environment is ready.",
    nextStep: "Review files or open wp-admin",
    ready: true,
  };
}

function buildLaunchAssistantProgress(
  selectedDomain: DomainRecord | null,
  installations: Installation[],
): {
  domainReady: boolean;
  sslReady: boolean;
  wordpressReady: boolean;
  completedSteps: number;
  totalSteps: number;
  nextStep: LaunchAssistantStep;
  ctaLabel: string;
} {
  const domainReady = !!selectedDomain;
  const sslReady =
    !!selectedDomain &&
    (selectedDomain.tls?.status === "issued" ||
      selectedDomain.tls?.status === "expiring" ||
      selectedDomain.tls?.status === "pending");

  const wordpressReady =
    !!selectedDomain &&
    installations.some(
      (item) =>
        item.domain.trim().toLowerCase() ===
        selectedDomain.hostname.trim().toLowerCase(),
    );

  const completedSteps =
    (domainReady ? 1 : 0) + (sslReady ? 1 : 0) + (wordpressReady ? 1 : 0);

  if (!domainReady) {
    return {
      domainReady,
      sslReady,
      wordpressReady,
      completedSteps,
      totalSteps: 3,
      nextStep: 1,
      ctaLabel: "Add your first domain",
    };
  }

  if (!sslReady) {
    return {
      domainReady,
      sslReady,
      wordpressReady,
      completedSteps,
      totalSteps: 3,
      nextStep: 2,
      ctaLabel: "Issue SSL certificate",
    };
  }

  if (!wordpressReady) {
    return {
      domainReady,
      sslReady,
      wordpressReady,
      completedSteps,
      totalSteps: 3,
      nextStep: 3,
      ctaLabel: "Install WordPress",
    };
  }

  return {
    domainReady,
    sslReady,
    wordpressReady,
    completedSteps,
    totalSteps: 3,
    nextStep: 4,
    ctaLabel: "Open your site",
  };
}



ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
