package provision

import (
	"archive/zip"
	"context"
	"crypto/rand"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

// DBAdminConfig defines privileged DB access used to create per-site users/databases.
type DBAdminConfig struct {
	Host     string
	Port     int
	User     string
	Password string
}

// Service handles one-click provisioning workloads for sites.
type Service struct {
	sitesRoot     string
	phpSocketPath string
	dbAdmin       DBAdminConfig
}

// NewService creates provisioning service.
func NewService(sitesRoot, phpSocketPath string, dbAdmin DBAdminConfig) *Service {
	return &Service{sitesRoot: sitesRoot, phpSocketPath: phpSocketPath, dbAdmin: dbAdmin}
}

// WordPressInstallRequest contains one-click install input.
type WordPressInstallRequest struct {
	Domain        string `json:"domain"`
	InstallPath   string `json:"installPath"`
	SiteTitle     string `json:"siteTitle"`
	AdminUser     string `json:"adminUser"`
	AdminPassword string `json:"adminPassword"`
	AdminEmail    string `json:"adminEmail"`
	DBName        string `json:"dbName"`
	DBUser        string `json:"dbUser"`
	DBPassword    string `json:"dbPassword"`
}

// WordPressInstallResult contains install summary.
type WordPressInstallResult struct {
	Domain                   string `json:"domain"`
	InstallPath              string `json:"installPath"`
	SitePath                 string `json:"sitePath"`
	URL                      string `json:"url"`
	AdminURL                 string `json:"adminUrl"`
	SiteTitle                string `json:"siteTitle"`
	AdminUser                string `json:"adminUser"`
	AdminPassword            string `json:"adminPassword"`
	AdminEmail               string `json:"adminEmail"`
	DBName                   string `json:"dbName"`
	DBUser                   string `json:"dbUser"`
	DBPassword               string `json:"dbPassword"`
	CredentialsAutoGenerated bool   `json:"credentialsAutoGenerated"`
	Message                  string `json:"message"`
}

var (
	domainRegexp      = regexp.MustCompile(`^[a-zA-Z0-9.-]+$`)
	installPathRegexp = regexp.MustCompile(`^/[a-zA-Z0-9/_-]*$`)
)

// InstallWordPress performs one-click WordPress provisioning.
func (s *Service) InstallWordPress(ctx context.Context, req WordPressInstallRequest) (WordPressInstallResult, error) {
	preparedReq, autoGenerated, err := applyRequestDefaults(req)
	if err != nil {
		return WordPressInstallResult{}, err
	}

	if err := validateRequest(preparedReq); err != nil {
		return WordPressInstallResult{}, err
	}

	if err := os.MkdirAll(s.sitesRoot, 0o755); err != nil {
		return WordPressInstallResult{}, fmt.Errorf("create sites root: %w", err)
	}

	installPath, err := normalizeInstallPath(preparedReq.InstallPath)
	if err != nil {
		return WordPressInstallResult{}, err
	}

	webRoot := filepath.Join(s.sitesRoot, preparedReq.Domain, "public_html")
	installTarget := webRoot
	if installPath != "/" {
		installTarget = filepath.Join(webRoot, strings.TrimPrefix(installPath, "/"))
	}

	if err := os.MkdirAll(installTarget, 0o755); err != nil {
		return WordPressInstallResult{}, fmt.Errorf("create install target: %w", err)
	}

	if err := s.downloadAndExtractWordPress(ctx, installTarget); err != nil {
		return WordPressInstallResult{}, err
	}

	if err := s.createDatabaseAndUser(ctx, preparedReq.DBName, preparedReq.DBUser, preparedReq.DBPassword); err != nil {
		return WordPressInstallResult{}, err
	}

	if err := writeWPConfig(installTarget, preparedReq); err != nil {
		return WordPressInstallResult{}, err
	}

	if err := writeNginxServerBlock(preparedReq.Domain, webRoot, s.phpSocketPath); err != nil {
		return WordPressInstallResult{}, err
	}

	if err := runCommand(ctx, "nginx", "-t"); err != nil {
		return WordPressInstallResult{}, fmt.Errorf("nginx config test failed: %w", err)
	}

	if err := runCommand(ctx, "systemctl", "reload", "nginx"); err != nil {
		return WordPressInstallResult{}, fmt.Errorf("reload nginx: %w", err)
	}

	if err := runCommand(ctx, "chown", "-R", "www-data:www-data", filepath.Join(s.sitesRoot, preparedReq.Domain)); err != nil {
		return WordPressInstallResult{}, fmt.Errorf("set ownership: %w", err)
	}

	if err := s.runWPInstall(ctx, installTarget, preparedReq, installPath); err != nil {
		return WordPressInstallResult{}, err
	}

	baseURL := "http://" + preparedReq.Domain
	if installPath != "/" {
		baseURL += installPath
	}

	return WordPressInstallResult{
		Domain:                   preparedReq.Domain,
		InstallPath:              installPath,
		SitePath:                 installTarget,
		URL:                      baseURL,
		AdminURL:                 strings.TrimRight(baseURL, "/") + "/wp-admin",
		SiteTitle:                preparedReq.SiteTitle,
		AdminUser:                preparedReq.AdminUser,
		AdminPassword:            preparedReq.AdminPassword,
		AdminEmail:               preparedReq.AdminEmail,
		DBName:                   preparedReq.DBName,
		DBUser:                   preparedReq.DBUser,
		DBPassword:               preparedReq.DBPassword,
		CredentialsAutoGenerated: autoGenerated,
		Message:                  "WordPress installed successfully",
	}, nil
}

func validateRequest(req WordPressInstallRequest) error {
	if req.Domain == "" || !domainRegexp.MatchString(req.Domain) {
		return errors.New("invalid domain")
	}
	if req.AdminEmail == "" || !strings.Contains(req.AdminEmail, "@") {
		return errors.New("valid adminEmail is required")
	}
	if req.SiteTitle == "" || req.AdminUser == "" || req.AdminPassword == "" {
		return errors.New("siteTitle, adminUser, adminPassword are required")
	}
	if req.DBName == "" || req.DBUser == "" || req.DBPassword == "" {
		return errors.New("dbName, dbUser, dbPassword are required")
	}
	if len(req.DBUser) > 32 {
		return errors.New("dbUser must be 32 characters or fewer")
	}
	if len(req.DBName) > 64 {
		return errors.New("dbName must be 64 characters or fewer")
	}
	if _, err := normalizeInstallPath(req.InstallPath); err != nil {
		return err
	}
	return nil
}

func applyRequestDefaults(req WordPressInstallRequest) (WordPressInstallRequest, bool, error) {
	req.Domain = strings.TrimSpace(req.Domain)
	req.InstallPath = strings.TrimSpace(req.InstallPath)
	req.SiteTitle = strings.TrimSpace(req.SiteTitle)
	req.AdminUser = strings.TrimSpace(req.AdminUser)
	req.AdminPassword = strings.TrimSpace(req.AdminPassword)
	req.AdminEmail = strings.TrimSpace(req.AdminEmail)
	req.DBName = strings.TrimSpace(req.DBName)
	req.DBUser = strings.TrimSpace(req.DBUser)
	req.DBPassword = strings.TrimSpace(req.DBPassword)

	base := sanitizeIdentifier(req.Domain)
	if base == "" {
		base = "site"
	}

	autoGenerated := false

	if req.SiteTitle == "" {
		req.SiteTitle = "WordPress on " + req.Domain
		autoGenerated = true
	}
	if req.AdminUser == "" {
		req.AdminUser = truncateIdentifier("admin_"+base, 32)
		autoGenerated = true
	}
	if req.AdminPassword == "" {
		value, err := randomCredential(20)
		if err != nil {
			return WordPressInstallRequest{}, false, fmt.Errorf("generate admin password: %w", err)
		}
		req.AdminPassword = value
		autoGenerated = true
	}
	if req.DBName == "" {
		req.DBName = truncateIdentifier("wp_"+base, 64)
		autoGenerated = true
	}
	if req.DBUser == "" {
		req.DBUser = truncateIdentifier("wpu_"+base, 32)
		autoGenerated = true
	}
	if req.DBPassword == "" {
		value, err := randomCredential(24)
		if err != nil {
			return WordPressInstallRequest{}, false, fmt.Errorf("generate db password: %w", err)
		}
		req.DBPassword = value
		autoGenerated = true
	}

	return req, autoGenerated, nil
}

func sanitizeIdentifier(input string) string {
	input = strings.ToLower(strings.TrimSpace(input))
	if input == "" {
		return "site"
	}

	var b strings.Builder
	b.Grow(len(input))
	for i := 0; i < len(input); i++ {
		ch := input[i]
		switch {
		case ch >= 'a' && ch <= 'z':
			b.WriteByte(ch)
		case ch >= '0' && ch <= '9':
			b.WriteByte(ch)
		case ch == '_' || ch == '-' || ch == '.':
			b.WriteByte('_')
		}
	}

	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "site"
	}
	return out
}

func truncateIdentifier(value string, maxLen int) string {
	if maxLen <= 0 {
		return ""
	}
	if len(value) <= maxLen {
		return value
	}
	out := strings.TrimRight(value[:maxLen], "_")
	if out == "" {
		return "site"
	}
	return out
}

func randomCredential(length int) (string, error) {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_"
	if length <= 0 {
		return "", errors.New("credential length must be positive")
	}

	buf := make([]byte, length)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}

	out := make([]byte, length)
	for i := 0; i < length; i++ {
		out[i] = alphabet[int(buf[i])%len(alphabet)]
	}
	return string(out), nil
}

func (s *Service) downloadAndExtractWordPress(ctx context.Context, sitePath string) error {
	tmpDir, err := os.MkdirTemp("", "panelx-wp-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	zipPath := filepath.Join(tmpDir, "wordpress.zip")
	if err := downloadFile(ctx, "https://wordpress.org/latest.zip", zipPath); err != nil {
		return err
	}

	if err := unzip(zipPath, tmpDir); err != nil {
		return err
	}

	source := filepath.Join(tmpDir, "wordpress")
	if err := copyDirContents(source, sitePath); err != nil {
		return err
	}
	return nil
}

func (s *Service) createDatabaseAndUser(_ context.Context, dbName, dbUser, dbPassword string) error {
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/", s.dbAdmin.User, s.dbAdmin.Password, s.dbAdmin.Host, s.dbAdmin.Port)
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return fmt.Errorf("open mysql connection: %w", err)
	}
	defer db.Close()

	queries := []string{
		fmt.Sprintf("CREATE DATABASE IF NOT EXISTS `%s` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", dbName),
		fmt.Sprintf("CREATE USER IF NOT EXISTS '%s'@'localhost' IDENTIFIED BY '%s'", dbUser, escapeSingleQuotes(dbPassword)),
		fmt.Sprintf("CREATE USER IF NOT EXISTS '%s'@'127.0.0.1' IDENTIFIED BY '%s'", dbUser, escapeSingleQuotes(dbPassword)),
		fmt.Sprintf("ALTER USER '%s'@'localhost' IDENTIFIED BY '%s'", dbUser, escapeSingleQuotes(dbPassword)),
		fmt.Sprintf("ALTER USER '%s'@'127.0.0.1' IDENTIFIED BY '%s'", dbUser, escapeSingleQuotes(dbPassword)),
		fmt.Sprintf("GRANT ALL PRIVILEGES ON `%s`.* TO '%s'@'localhost'", dbName, dbUser),
		fmt.Sprintf("GRANT ALL PRIVILEGES ON `%s`.* TO '%s'@'127.0.0.1'", dbName, dbUser),
		"FLUSH PRIVILEGES",
	}

	for _, query := range queries {
		if _, err := db.Exec(query); err != nil {
			return fmt.Errorf("execute sql query failed: %w", err)
		}
	}

	return nil
}

func writeWPConfig(sitePath string, req WordPressInstallRequest) error {
	salts, err := randomSalts(8)
	if err != nil {
		return err
	}

	wpConfig := fmt.Sprintf(`<?php

define('DB_NAME', '%s');
define('DB_USER', '%s');
define('DB_PASSWORD', '%s');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

define('AUTH_KEY',         '%s');
define('SECURE_AUTH_KEY',  '%s');
define('LOGGED_IN_KEY',    '%s');
define('NONCE_KEY',        '%s');
define('AUTH_SALT',        '%s');
define('SECURE_AUTH_SALT', '%s');
define('LOGGED_IN_SALT',   '%s');
define('NONCE_SALT',       '%s');

$table_prefix = 'wp_';
define('WP_DEBUG', false);

if ( ! defined('ABSPATH') ) {
	define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
`, req.DBName, req.DBUser, req.DBPassword,
		salts[0], salts[1], salts[2], salts[3], salts[4], salts[5], salts[6], salts[7],
	)

	configPath := filepath.Join(sitePath, "wp-config.php")
	if err := os.WriteFile(configPath, []byte(wpConfig), 0o640); err != nil {
		return fmt.Errorf("write wp-config.php: %w", err)
	}

	return nil
}

func writeNginxServerBlock(domain, sitePath, phpSocketPath string) error {
	conf := fmt.Sprintf(`server {
    listen 80;
    server_name %s;

    root %s;
    index index.php index.html index.htm;

    access_log /var/log/nginx/%s.access.log;
    error_log /var/log/nginx/%s.error.log;

    client_max_body_size 128M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:%s;
    }

    location ~ /\.ht {
        deny all;
    }
}
`, domain, sitePath, domain, domain, phpSocketPath)

	available := filepath.Join("/etc/nginx/sites-available", domain+".conf")
	enabled := filepath.Join("/etc/nginx/sites-enabled", domain+".conf")
	if err := os.WriteFile(available, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("write nginx config: %w", err)
	}

	_ = os.Remove(enabled)
	if err := os.Symlink(available, enabled); err != nil {
		return fmt.Errorf("enable nginx site: %w", err)
	}

	return nil
}

func (s *Service) runWPInstall(ctx context.Context, sitePath string, req WordPressInstallRequest, installPath string) error {
	url := "http://" + req.Domain
	if installPath != "/" {
		url += installPath
	}

	if err := runCommand(ctx, "wp", "core", "install",
		"--allow-root",
		"--path="+sitePath,
		"--url="+url,
		"--title="+req.SiteTitle,
		"--admin_user="+req.AdminUser,
		"--admin_password="+req.AdminPassword,
		"--admin_email="+req.AdminEmail,
		"--skip-email"); err != nil {
		return fmt.Errorf("run wp core install: %w", err)
	}
	return nil
}

func downloadFile(ctx context.Context, url, target string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}

	client := &http.Client{Timeout: 5 * time.Minute}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("download %s: %w", url, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		return fmt.Errorf("download %s failed: %s", url, resp.Status)
	}

	file, err := os.Create(target)
	if err != nil {
		return fmt.Errorf("create %s: %w", target, err)
	}
	defer file.Close()

	if _, err := io.Copy(file, resp.Body); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}
	return nil
}

func unzip(sourceZip, destination string) error {
	r, err := zip.OpenReader(sourceZip)
	if err != nil {
		return fmt.Errorf("open zip: %w", err)
	}
	defer r.Close()

	for _, f := range r.File {
		path := filepath.Join(destination, f.Name)
		if !strings.HasPrefix(path, filepath.Clean(destination)+string(os.PathSeparator)) {
			return errors.New("invalid zip path traversal")
		}

		if f.FileInfo().IsDir() {
			if err := os.MkdirAll(path, f.Mode()); err != nil {
				return fmt.Errorf("mkdir %s: %w", path, err)
			}
			continue
		}

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("mkdir parent for %s: %w", path, err)
		}

		in, err := f.Open()
		if err != nil {
			return fmt.Errorf("open zip file %s: %w", f.Name, err)
		}

		out, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode())
		if err != nil {
			in.Close()
			return fmt.Errorf("create extracted file %s: %w", path, err)
		}

		if _, err := io.Copy(out, in); err != nil {
			in.Close()
			out.Close()
			return fmt.Errorf("extract %s: %w", path, err)
		}

		in.Close()
		out.Close()
	}

	return nil
}

func copyDirContents(source, destination string) error {
	entries, err := os.ReadDir(source)
	if err != nil {
		return fmt.Errorf("read source dir: %w", err)
	}

	for _, entry := range entries {
		srcPath := filepath.Join(source, entry.Name())
		dstPath := filepath.Join(destination, entry.Name())

		if entry.IsDir() {
			if err := os.MkdirAll(dstPath, 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", dstPath, err)
			}
			if err := copyDirContents(srcPath, dstPath); err != nil {
				return err
			}
			continue
		}

		in, err := os.Open(srcPath)
		if err != nil {
			return fmt.Errorf("open %s: %w", srcPath, err)
		}

		out, err := os.OpenFile(dstPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
		if err != nil {
			in.Close()
			return fmt.Errorf("create %s: %w", dstPath, err)
		}

		if _, err := io.Copy(out, in); err != nil {
			in.Close()
			out.Close()
			return fmt.Errorf("copy %s to %s: %w", srcPath, dstPath, err)
		}

		in.Close()
		out.Close()
	}

	return nil
}

func runCommand(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("command %s %v failed: %w output=%s", name, args, err, string(output))
	}
	return nil
}

func randomSalts(count int) ([]string, error) {
	out := make([]string, 0, count)
	for i := 0; i < count; i++ {
		buf := make([]byte, 48)
		if _, err := rand.Read(buf); err != nil {
			return nil, fmt.Errorf("generate random bytes: %w", err)
		}
		out = append(out, fmt.Sprintf("%x", buf))
	}
	return out, nil
}

func escapeSingleQuotes(value string) string {
	return strings.ReplaceAll(value, "'", "''")
}

func normalizeInstallPath(input string) (string, error) {
	trimmed := strings.TrimSpace(input)
	if trimmed == "" || trimmed == "/" {
		return "/", nil
	}

	normalizedInput := strings.ReplaceAll(trimmed, "\\", "/")
	for _, segment := range strings.Split(normalizedInput, "/") {
		if segment == "." || segment == ".." {
			return "", errors.New("installPath contains invalid traversal")
		}
	}

	if !strings.HasPrefix(normalizedInput, "/") {
		normalizedInput = "/" + normalizedInput
	}

	cleaned := filepath.ToSlash(filepath.Clean(normalizedInput))
	if !strings.HasPrefix(cleaned, "/") {
		cleaned = "/" + cleaned
	}

	if cleaned != "/" {
		cleaned = strings.TrimSuffix(cleaned, "/")
	}

	if !installPathRegexp.MatchString(cleaned) {
		return "", errors.New("installPath contains invalid characters")
	}

	return cleaned, nil
}
